package com.ai_kids_care.v1.security;

public enum AuthorizationAction {
    PLATFORM_METADATA_READ,
    PLATFORM_METADATA_WRITE,
    TENANT_ANNOUNCEMENT_READ,
    TENANT_ANNOUNCEMENT_WRITE,
    TENANT_S2_READ,
    TENANT_S2_WRITE,
    TENANT_SURVEILLANCE_READ,
    // SPEC-0002 Slice A: 园级审批 / 成员状态变更（粗粒度 role 门；细粒度在 KindergartenAdminPolicy 内完成）
    KINDERGARTEN_ADMIN_APPROVAL_READ,
    KINDERGARTEN_ADMIN_APPROVAL_WRITE,
    KINDERGARTEN_ADMIN_MEMBER_WRITE
}
