/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.model.Classes;
import com.ai_kids_care.v1.model.ClassesCreateRequest;
import com.ai_kids_care.v1.model.ClassesUpdateRequest;
import com.ai_kids_care.v1.model.ErrorResponse;
import org.springframework.lang.Nullable;
import com.ai_kids_care.v1.model.PageOfClasses;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")
@Validated
@Tag(name = "Classes", description = "the Classes API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface ClassesApi {

    String PATH_CREATE_CLASSES = "/v1/classes";
    /**
     * POST /v1/classes : Create classes
     *
     * @param classesCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createClasses",
        summary = "Create classes",
        tags = { "Classes" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Classes.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ClassesApi.PATH_CREATE_CLASSES,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    Classes createClasses(
        @Parameter(name = "ClassesCreateRequest", description = "", required = true) @Valid @RequestBody ClassesCreateRequest classesCreateRequest
    );


    String PATH_DELETE_CLASSES = "/v1/classes/{class_id}";
    /**
     * DELETE /v1/classes/{class_id} : Delete classes by class_id
     *
     * @param classId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteClasses",
        summary = "Delete classes by class_id",
        tags = { "Classes" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ClassesApi.PATH_DELETE_CLASSES,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteClasses(
        @NotNull @Parameter(name = "class_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("class_id") Long classId
    );


    String PATH_GET_CLASSES = "/v1/classes/{class_id}";
    /**
     * GET /v1/classes/{class_id} : Get classes by class_id
     *
     * @param classId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getClasses",
        summary = "Get classes by class_id",
        tags = { "Classes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Classes.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ClassesApi.PATH_GET_CLASSES,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    Classes getClasses(
        @NotNull @Parameter(name = "class_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("class_id") Long classId
    );


    String PATH_LIST_CLASSES = "/v1/classes";
    /**
     * GET /v1/classes : List classes
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listClasses",
        summary = "List classes",
        tags = { "Classes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfClasses.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ClassesApi.PATH_LIST_CLASSES,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfClasses listClasses(
        @Min(value = 0) @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false) @Nullable Integer page,
        @Min(value = 1) @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false) @Nullable Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sort", required = false) @Nullable String sort
    );


    String PATH_UPDATE_CLASSES = "/v1/classes/{class_id}";
    /**
     * PUT /v1/classes/{class_id} : Update classes by class_id
     *
     * @param classId  (required)
     * @param classesUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateClasses",
        summary = "Update classes by class_id",
        tags = { "Classes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Classes.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = ClassesApi.PATH_UPDATE_CLASSES,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    Classes updateClasses(
        @NotNull @Parameter(name = "class_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("class_id") Long classId,
        @Parameter(name = "ClassesUpdateRequest", description = "", required = true) @Valid @RequestBody ClassesUpdateRequest classesUpdateRequest
    );

}
