/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.model.ErrorResponse;
import com.ai_kids_care.v1.model.EventEvidenceFiles;
import com.ai_kids_care.v1.model.EventEvidenceFilesCreateRequest;
import com.ai_kids_care.v1.model.EventEvidenceFilesUpdateRequest;
import org.springframework.lang.Nullable;
import com.ai_kids_care.v1.model.PageOfEventEvidenceFiles;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")
@Validated
@Tag(name = "EventEvidenceFiles", description = "the EventEvidenceFiles API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface EventEvidenceFilesApi {

    String PATH_CREATE_EVENT_EVIDENCE_FILES = "/v1/event_evidence_files";
    /**
     * POST /v1/event_evidence_files : Create event_evidence_files
     *
     * @param eventEvidenceFilesCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createEventEvidenceFiles",
        summary = "Create event_evidence_files",
        tags = { "EventEvidenceFiles" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventEvidenceFiles.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = EventEvidenceFilesApi.PATH_CREATE_EVENT_EVIDENCE_FILES,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    EventEvidenceFiles createEventEvidenceFiles(
        @Parameter(name = "EventEvidenceFilesCreateRequest", description = "", required = true) @Valid @RequestBody EventEvidenceFilesCreateRequest eventEvidenceFilesCreateRequest
    );


    String PATH_DELETE_EVENT_EVIDENCE_FILES = "/v1/event_evidence_files/{evidence_id}";
    /**
     * DELETE /v1/event_evidence_files/{evidence_id} : Delete event_evidence_files by evidence_id
     *
     * @param evidenceId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteEventEvidenceFiles",
        summary = "Delete event_evidence_files by evidence_id",
        tags = { "EventEvidenceFiles" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = EventEvidenceFilesApi.PATH_DELETE_EVENT_EVIDENCE_FILES,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteEventEvidenceFiles(
        @NotNull @Parameter(name = "evidence_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("evidence_id") Long evidenceId
    );


    String PATH_GET_EVENT_EVIDENCE_FILES = "/v1/event_evidence_files/{evidence_id}";
    /**
     * GET /v1/event_evidence_files/{evidence_id} : Get event_evidence_files by evidence_id
     *
     * @param evidenceId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getEventEvidenceFiles",
        summary = "Get event_evidence_files by evidence_id",
        tags = { "EventEvidenceFiles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventEvidenceFiles.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = EventEvidenceFilesApi.PATH_GET_EVENT_EVIDENCE_FILES,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    EventEvidenceFiles getEventEvidenceFiles(
        @NotNull @Parameter(name = "evidence_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("evidence_id") Long evidenceId
    );


    String PATH_LIST_EVENT_EVIDENCE_FILES = "/v1/event_evidence_files";
    /**
     * GET /v1/event_evidence_files : List event_evidence_files
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listEventEvidenceFiles",
        summary = "List event_evidence_files",
        tags = { "EventEvidenceFiles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfEventEvidenceFiles.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = EventEvidenceFilesApi.PATH_LIST_EVENT_EVIDENCE_FILES,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfEventEvidenceFiles listEventEvidenceFiles(
        @Min(value = 0) @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false) @Nullable Integer page,
        @Min(value = 1) @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false) @Nullable Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sort", required = false) @Nullable String sort
    );


    String PATH_UPDATE_EVENT_EVIDENCE_FILES = "/v1/event_evidence_files/{evidence_id}";
    /**
     * PUT /v1/event_evidence_files/{evidence_id} : Update event_evidence_files by evidence_id
     *
     * @param evidenceId  (required)
     * @param eventEvidenceFilesUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateEventEvidenceFiles",
        summary = "Update event_evidence_files by evidence_id",
        tags = { "EventEvidenceFiles" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventEvidenceFiles.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = EventEvidenceFilesApi.PATH_UPDATE_EVENT_EVIDENCE_FILES,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    EventEvidenceFiles updateEventEvidenceFiles(
        @NotNull @Parameter(name = "evidence_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("evidence_id") Long evidenceId,
        @Parameter(name = "EventEvidenceFilesUpdateRequest", description = "", required = true) @Valid @RequestBody EventEvidenceFilesUpdateRequest eventEvidenceFilesUpdateRequest
    );

}
