/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.model.ErrorResponse;
import org.springframework.lang.Nullable;
import com.ai_kids_care.v1.model.PageOfRoomCameraAssignments;
import com.ai_kids_care.v1.model.RoomCameraAssignments;
import com.ai_kids_care.v1.model.RoomCameraAssignmentsCreateRequest;
import com.ai_kids_care.v1.model.RoomCameraAssignmentsUpdateRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")
@Validated
@Tag(name = "RoomCameraAssignments", description = "the RoomCameraAssignments API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface RoomCameraAssignmentsApi {

    String PATH_CREATE_ROOM_CAMERA_ASSIGNMENTS = "/v1/room_camera_assignments";
    /**
     * POST /v1/room_camera_assignments : Create room_camera_assignments
     *
     * @param roomCameraAssignmentsCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createRoomCameraAssignments",
        summary = "Create room_camera_assignments",
        tags = { "RoomCameraAssignments" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RoomCameraAssignments.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = RoomCameraAssignmentsApi.PATH_CREATE_ROOM_CAMERA_ASSIGNMENTS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    RoomCameraAssignments createRoomCameraAssignments(
        @Parameter(name = "RoomCameraAssignmentsCreateRequest", description = "", required = true) @Valid @RequestBody RoomCameraAssignmentsCreateRequest roomCameraAssignmentsCreateRequest
    );


    String PATH_DELETE_ROOM_CAMERA_ASSIGNMENTS = "/v1/room_camera_assignments/{assignment_id}";
    /**
     * DELETE /v1/room_camera_assignments/{assignment_id} : Delete room_camera_assignments by assignment_id
     *
     * @param assignmentId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteRoomCameraAssignments",
        summary = "Delete room_camera_assignments by assignment_id",
        tags = { "RoomCameraAssignments" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = RoomCameraAssignmentsApi.PATH_DELETE_ROOM_CAMERA_ASSIGNMENTS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteRoomCameraAssignments(
        @NotNull @Parameter(name = "assignment_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("assignment_id") Long assignmentId
    );


    String PATH_GET_ROOM_CAMERA_ASSIGNMENTS = "/v1/room_camera_assignments/{assignment_id}";
    /**
     * GET /v1/room_camera_assignments/{assignment_id} : Get room_camera_assignments by assignment_id
     *
     * @param assignmentId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getRoomCameraAssignments",
        summary = "Get room_camera_assignments by assignment_id",
        tags = { "RoomCameraAssignments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RoomCameraAssignments.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = RoomCameraAssignmentsApi.PATH_GET_ROOM_CAMERA_ASSIGNMENTS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    RoomCameraAssignments getRoomCameraAssignments(
        @NotNull @Parameter(name = "assignment_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("assignment_id") Long assignmentId
    );


    String PATH_LIST_ROOM_CAMERA_ASSIGNMENTS = "/v1/room_camera_assignments";
    /**
     * GET /v1/room_camera_assignments : List room_camera_assignments
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listRoomCameraAssignments",
        summary = "List room_camera_assignments",
        tags = { "RoomCameraAssignments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfRoomCameraAssignments.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = RoomCameraAssignmentsApi.PATH_LIST_ROOM_CAMERA_ASSIGNMENTS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfRoomCameraAssignments listRoomCameraAssignments(
        @Min(value = 0) @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false) @Nullable Integer page,
        @Min(value = 1) @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false) @Nullable Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sort", required = false) @Nullable String sort
    );


    String PATH_UPDATE_ROOM_CAMERA_ASSIGNMENTS = "/v1/room_camera_assignments/{assignment_id}";
    /**
     * PUT /v1/room_camera_assignments/{assignment_id} : Update room_camera_assignments by assignment_id
     *
     * @param assignmentId  (required)
     * @param roomCameraAssignmentsUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateRoomCameraAssignments",
        summary = "Update room_camera_assignments by assignment_id",
        tags = { "RoomCameraAssignments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RoomCameraAssignments.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = RoomCameraAssignmentsApi.PATH_UPDATE_ROOM_CAMERA_ASSIGNMENTS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    RoomCameraAssignments updateRoomCameraAssignments(
        @NotNull @Parameter(name = "assignment_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("assignment_id") Long assignmentId,
        @Parameter(name = "RoomCameraAssignmentsUpdateRequest", description = "", required = true) @Valid @RequestBody RoomCameraAssignmentsUpdateRequest roomCameraAssignmentsUpdateRequest
    );

}
