-- V12: notification delivery-attempt / idempotency storage (PRF-02 delivery atomicity).
--
-- One attempt row per notification (UNIQUE notification_id, UNIQUE idempotency_key) records that an
-- external delivery was begun (IN_FLIGHT) and its terminal outcome (SUCCEEDED / FAILED). The unique
-- key is the at-most-once guard: NotificationService commits the IN_FLIGHT attempt + SENDING in a short
-- transaction BEFORE the provider call, so a retry of a notification that already has an attempt row
-- never re-invokes the provider (design Decision 2). outcome/provider are plain varchars (no new PG
-- enum) to keep this migration additive.
--
-- Additive + non-destructive: runs forward in BOTH schema paths (fresh-V1 Flyway and initdb+baseline).
-- The initdb baseline mirrors V1 only (per the V9 precedent and baseline-on-migrate=true), so this
-- table is NOT mirrored there -- both paths obtain it from this migration.

CREATE TABLE "notification_delivery_attempts" (
  "attempt_id"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notification_id"  bigint NOT NULL,
  "idempotency_key"  varchar NOT NULL,
  "channel"          notification_channel_enum NOT NULL,
  "provider"         varchar,
  "outcome"          varchar NOT NULL,
  "detail"           varchar,
  "created_at"       timestamptz NOT NULL DEFAULT now(),
  "updated_at"       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "uq_notif_delivery_attempt_notification" UNIQUE ("notification_id"),
  CONSTRAINT "uq_notif_delivery_attempt_idem" UNIQUE ("idempotency_key"),
  CONSTRAINT "fk_notif_delivery_attempt_notification"
      FOREIGN KEY ("notification_id") REFERENCES "notifications" ("notification_id") ON DELETE CASCADE
);

CREATE INDEX "idx_notif_delivery_attempt_outcome" ON "notification_delivery_attempts" ("outcome");

COMMENT ON TABLE "notification_delivery_attempts" IS
  'Per-notification external-delivery attempt + idempotency record (PRF-02). UNIQUE(notification_id) enforces at-most-once provider call on the retry path.';
