-- V7: Replace the FCM/APNS-shaped `device_tokens` table with a provider-aware
-- `push_subscriptions` table.
--
-- Rationale: the chosen PUSH channel is Pushover, which addresses recipients by a
-- per-user "user key" (platform-agnostic), not by per-device platform push tokens.
-- `device_tokens` (device_platform_enum + push_token, unique per platform) never fit
-- Pushover. The device-token management API was never published, so the table is empty
-- in production — it is dropped and replaced rather than data-migrated.
--
-- Both schema paths have `device_tokens` before this migration runs: the fresh path
-- creates it in V1; the initdb/demo path creates it from db/initdb (a V1 mirror) before
-- Flyway baselines V1. See OpenSpec change wire-push-notification-delivery.

DROP TABLE IF EXISTS "device_tokens";
DROP TYPE IF EXISTS "device_platform_enum";

CREATE TYPE "push_provider_enum" AS ENUM (
  'PUSHOVER'
);

CREATE TABLE "push_subscriptions" (
  "push_subscription_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "provider" push_provider_enum NOT NULL,
  "address" varchar NOT NULL,
  "device_label" varchar,
  "status" status_enum NOT NULL,
  "last_verified_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE UNIQUE INDEX "uq_push_subscriptions_user_provider_address"
  ON "push_subscriptions" ("user_id", "provider", "address");
CREATE INDEX "idx_push_subscriptions_user_status"
  ON "push_subscriptions" ("user_id", "status");

ALTER TABLE "push_subscriptions"
  ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

COMMENT ON TABLE  "push_subscriptions"                 IS '사용자별 PUSH 전송 신원(제공자 인식). device_tokens 대체';
COMMENT ON COLUMN "push_subscriptions"."provider"      IS 'PUSH 제공자(현재 PUSHOVER)';
COMMENT ON COLUMN "push_subscriptions"."address"       IS '제공자 전송 주소(Pushover=user key)';
COMMENT ON COLUMN "push_subscriptions"."device_label"  IS '선택: Pushover 디바이스명/사람용 라벨';
COMMENT ON COLUMN "push_subscriptions"."status"        IS '구독 상태';
