-- Timezone setup (KST)
SET TIME ZONE 'Asia/Seoul';

DO $$
DECLARE
    db_name text := current_database();
BEGIN
    EXECUTE format('ALTER DATABASE %I SET timezone TO %L', db_name, 'Asia/Seoul');
END $$;

-- User account table
CREATE TABLE IF NOT EXISTS user_account (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    login_id VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    user_email VARCHAR(255) NOT NULL,
    user_tel VARCHAR(255) NOT NULL,
    status VARCHAR(50),
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON COLUMN user_account.user_id IS '사용자 계정 ID';
COMMENT ON COLUMN user_account.user_name IS '사용자 이름';
COMMENT ON COLUMN user_account.login_id IS '로그인 ID(사용자 식별자)';
COMMENT ON COLUMN user_account.password_hash IS '비밀번호 해시';
COMMENT ON COLUMN user_account.user_email IS '사용자 이메일';
COMMENT ON COLUMN user_account.user_tel IS '사용자 전화번호';
COMMENT ON COLUMN user_account.status IS '계정 상태(ACTIVE/LOCKED/DISABLED 등)';

COMMENT ON COLUMN user_account.last_login_at IS '마지막 로그인 일시';

COMMENT ON COLUMN user_account.created_at IS '생성 일시';

COMMENT ON COLUMN user_account.updated_at IS '수정 일시';



-- Initial accounts (password: password - BCrypt encoded)
INSERT INTO user_account ( user_name, login_id, password_hash, user_email, user_tel, status, created_at, updated_at)
SELECT '관리자', 'admin', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'admin@example.com', '010-0000-0000', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM user_account WHERE login_id = 'admin');

INSERT INTO user_account (user_name, login_id, password_hash, user_email, user_tel, status, created_at, updated_at)
SELECT '일반사용자', 'user', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user@example.com', '010-1111-1111', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM user_account WHERE login_id = 'user');



-- Dashboard metrics table
CREATE TABLE IF NOT EXISTS dashboard_metrics (
    id BIGSERIAL PRIMARY KEY,
    metric_name VARCHAR(255) NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    unit VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);



-- Initial dashboard metrics
INSERT INTO dashboard_metrics (metric_name, value, unit, created_at) VALUES
('CPU 사용률', 65.5, '%', CURRENT_TIMESTAMP),
('메모리 사용량', 78.2, '%', CURRENT_TIMESTAMP),
('디스크 사용량', 45.0, '%', CURRENT_TIMESTAMP),
('네트워크 트래픽', 120.5, 'Mbps', CURRENT_TIMESTAMP),
('API 응답 시간', 95.0, 'ms', CURRENT_TIMESTAMP),
('활성 사용자', 234.0, '명', CURRENT_TIMESTAMP);
