-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2026-03-11T14:38:29.552Z

CREATE TYPE "status_enum" AS ENUM (
  'ACTIVE',
  'PENDING',
  'DISABLED'
);

CREATE TYPE "user_role_enum" AS ENUM (
  'GUARDIAN',
  'TEACHER',
  'KINDERGARTEN_ADMIN',
  'PLATFORM_IT_ADMIN',
  'SUPERADMIN'
);

CREATE TYPE "user_role_assignment_scope_type" AS ENUM (
  'PLATFORM',
  'KINDERGARTEN'
);

CREATE TYPE "notification_target_type" AS ENUM (
  'ROOM',
  'CAMERA',
  'KINDERGARTEN'
);

CREATE TYPE "event_status_enum" AS ENUM (
  'OPEN',
  'ACKNOWLEDGED',
  'IN_REVIEW',
  'RESOLVED',
  'DISMISSED',
  'ESCALATED'
);

CREATE TYPE "notification_status_enum" AS ENUM (
  'QUEUED',
  'SENDING',
  'SENT',
  'DELIVERED',
  'READ',
  'FAILED',
  'CANCELED'
);

CREATE TYPE "camera_stream_type_enum" AS ENUM (
  'MAIN',
  'SUB',
  'SNAPSHOT',
  'RECORDING',
  'OTHER'
);

CREATE TABLE "users" (
  "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login_id" varchar UNIQUE,
  "email" varchar,
  "phone" varchar,
  "password_hash" varchar,
  "status" status_enum,
  "last_login_at" timestamptz,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "kindergartens" (
  "kindergarten_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "address" varchar,
  "region_code" varchar,
  "code" varchar,
  "business_registration_no" varchar,
  "contact_name" varchar,
  "contact_phone" varchar,
  "contact_email" varchar,
  "status" status_enum,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "classes" (
  "class_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kindergarten_id" bigint NOT NULL,
  "name" varchar,
  "grade" varchar,
  "academic_year" bigint,
  "start_date" date,
  "end_date" date,
  "status" status_enum,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "children" (
  "child_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kindergarten_id" bigint NOT NULL,
  "name" varchar,
  "child_no" varchar,
  "rrn_encrypted" varchar,
  "rrn_first6" varchar,
  "birth_date" date,
  "gender" varchar,
  "address" varchar,
  "enroll_date" date,
  "leave_date" date,
  "status" status_enum,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "child_class_assignments" (
  "assignment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kindergarten_id" bigint NOT NULL,
  "child_id" bigint NOT NULL,
  "class_id" bigint NOT NULL,
  "start_date" date,
  "end_date" date,
  "reason" varchar,
  "note" varchar,
  "status" status_enum,
  "created_by_user_id" bigint,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "teachers" (
  "teacher_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kindergarten_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "staff_no" varchar,
  "name" varchar,
  "gender" varchar,
  "emergency_contact_name" varchar,
  "emergency_contact_phone" varchar,
  "rrn_encrypted" varchar,
  "rrn_first6" varchar,
  "level" varchar,
  "start_date" date,
  "end_date" date,
  "status" status_enum,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "superadmins" (
  "superadmin_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "name" varchar NOT NULL,
  "department" varchar,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "class_teacher_assignments" (
  "assignment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kindergarten_id" bigint NOT NULL,
  "class_id" bigint NOT NULL,
  "teacher_id" bigint NOT NULL,
  "role" varchar,
  "start_date" date,
  "end_date" date,
  "reason" varchar,
  "note" varchar,
  "status" status_enum,
  "created_by_user_id" bigint,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "rooms" (
  "room_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kindergarten_id" bigint NOT NULL,
  "name" varchar,
  "room_code" varchar,
  "location_note" varchar,
  "room_type" varchar,
  "status" status_enum,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "class_room_assignments" (
  "assignment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kindergarten_id" bigint NOT NULL,
  "class_id" bigint NOT NULL,
  "room_id" bigint NOT NULL,
  "start_at" timestamptz NOT NULL,
  "end_at" timestamptz,
  "purpose" varchar,
  "note" varchar,
  "status" status_enum,
  "created_by_user_id" bigint,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "cctv_cameras" (
  "camera_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kindergarten_id" bigint NOT NULL,
  "serial_no" varchar,
  "camera_name" varchar,
  "model" varchar,
  "created_by_user_id" bigint,
  "status" status_enum,
  "last_seen_at" timestamptz,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "room_camera_assignments" (
  "assignment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kindergarten_id" bigint NOT NULL,
  "camera_id" bigint NOT NULL,
  "room_id" bigint NOT NULL,
  "start_at" timestamptz NOT NULL DEFAULT 'now()',
  "end_at" timestamptz,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "guardians" (
  "guardian_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kindergarten_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "name" varchar,
  "rrn_encrypted" varchar,
  "rrn_first6" varchar,
  "gender" varchar,
  "address" varchar,
  "status" status_enum,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "child_guardian_relationships" (
  "kindergarten_id" bigint NOT NULL,
  "child_id" bigint NOT NULL,
  "guardian_id" bigint NOT NULL,
  "relationship" varchar,
  "is_primary" boolean,
  "priority" int,
  "start_date" date,
  "end_date" date,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()',
  PRIMARY KEY ("kindergarten_id", "child_id", "guardian_id")
);

CREATE TABLE "user_kindergarten_memberships" (
  "membership_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "kindergarten_id" bigint NOT NULL,
  "status" status_enum,
  "joined_at" timestamptz DEFAULT 'now()',
  "left_at" timestamptz,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "user_role_assignments" (
  "role_assignment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "role" user_role_enum,
  "scope_type" user_role_assignment_scope_type,
  "scope_id" bigint,
  "status" status_enum,
  "granted_at" timestamptz DEFAULT 'now()',
  "granted_by_user_id" bigint,
  "revoked_at" timestamptz
);

CREATE TABLE "camera_streams" (
  "stream_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kindergarten_id" bigint NOT NULL,
  "camera_id" bigint NOT NULL,
  "stream_type" camera_stream_type_enum,
  "stream_url" varchar,
  "stream_user" varchar,
  "stream_password_encrypted" varchar,
  "protocol" varchar,
  "fps" int,
  "resolution" varchar,
  "is_primary" boolean,
  "enabled" boolean,
  "status" status_enum,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "ai_models" (
  "model_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "version" varchar,
  "status" status_enum,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "detection_sessions" (
  "session_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kindergarten_id" bigint NOT NULL,
  "camera_id" bigint NOT NULL,
  "stream_id" bigint NOT NULL,
  "model_id" bigint NOT NULL,
  "started_at" timestamptz DEFAULT 'now()',
  "ended_at" timestamptz,
  "status" status_enum,
  "avg_latency_ms" int,
  "inference_fps" float
);

CREATE TABLE "detection_events" (
  "event_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kindergarten_id" bigint NOT NULL,
  "camera_id" bigint NOT NULL,
  "room_id" bigint NOT NULL,
  "session_id" bigint NOT NULL,
  "event_type" varchar,
  "severity" int,
  "confidence" float,
  "detected_at" timestamptz DEFAULT 'now()',
  "start_time" timestamptz,
  "end_time" timestamptz,
  "status" event_status_enum,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "event_reviews" (
  "review_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" bigint NOT NULL,
  "kindergarten_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "action" varchar,
  "from_status" event_status_enum,
  "result_status" event_status_enum,
  "comment" varchar,
  "created_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "event_evidence_files" (
  "evidence_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" bigint NOT NULL,
  "kindergarten_id" bigint NOT NULL,
  "type" varchar,
  "storage_uri" varchar,
  "mime_type" varchar,
  "created_at" timestamptz DEFAULT 'now()',
  "retention_until" timestamptz,
  "hold" boolean,
  "hash" varchar
);

CREATE TABLE "device_tokens" (
  "device_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "platform" varchar,
  "push_token" varchar,
  "status" status_enum,
  "last_seen_at" timestamptz,
  "created_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "notification_rules" (
  "rule_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kindergarten_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "target_type" notification_target_type,
  "target_id" bigint,
  "event_type" varchar,
  "min_severity" int,
  "quiet_hours_json" varchar,
  "enabled" boolean,
  "created_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "notifications" (
  "notification_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kindergarten_id" bigint NOT NULL,
  "event_id" bigint NOT NULL,
  "recipient_user_id" bigint NOT NULL,
  "channel" varchar,
  "title" varchar,
  "body" varchar,
  "status" notification_status_enum,
  "dedupe_key" varchar,
  "sent_at" timestamptz,
  "fail_reason" varchar,
  "retry_count" int,
  "created_at" timestamptz DEFAULT 'now()'
);

CREATE TABLE "audit_logs" (
  "audit_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kindergarten_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "action" varchar,
  "resource_type" varchar,
  "resource_id" bigint,
  "ip" varchar,
  "user_agent" varchar,
  "created_at" timestamptz DEFAULT 'now()'
);

CREATE UNIQUE INDEX "uq_user_account_login_id" ON "users" ("login_id");

CREATE UNIQUE INDEX "uq_user_account_email" ON "users" ("email");

CREATE UNIQUE INDEX "uq_user_account_phone" ON "users" ("phone");

CREATE UNIQUE INDEX "uq_class_kg_classid" ON "classes" ("kindergarten_id", "class_id");

CREATE UNIQUE INDEX "uq_child_kg_childid" ON "children" ("kindergarten_id", "child_id");

CREATE UNIQUE INDEX "uq_child_kg_childno" ON "children" ("kindergarten_id", "child_no");

CREATE INDEX "idx_cca_child" ON "child_class_assignments" ("kindergarten_id", "child_id");

CREATE INDEX "idx_cca_child_time" ON "child_class_assignments" ("kindergarten_id", "child_id", "start_date", "end_date");

CREATE INDEX "idx_cca_class_time" ON "child_class_assignments" ("kindergarten_id", "class_id", "start_date", "end_date");

CREATE UNIQUE INDEX "uq_teacher_kg_teacherid" ON "teachers" ("kindergarten_id", "teacher_id");

CREATE UNIQUE INDEX "uq_teacher_kg_staffno" ON "teachers" ("kindergarten_id", "staff_no");

CREATE UNIQUE INDEX "uq_teacher_user_id" ON "teachers" ("user_id");

CREATE UNIQUE INDEX "uq_superadmin_userid" ON "superadmins" ("user_id");

CREATE INDEX "idx_cta_class_time" ON "class_teacher_assignments" ("kindergarten_id", "class_id", "start_date", "end_date");

CREATE INDEX "idx_cta_teacher_time" ON "class_teacher_assignments" ("kindergarten_id", "teacher_id", "start_date", "end_date");

CREATE UNIQUE INDEX "uq_room_kg_roomid" ON "rooms" ("kindergarten_id", "room_id");

CREATE UNIQUE INDEX "uq_room_kg_roomcode" ON "rooms" ("kindergarten_id", "room_code");

CREATE INDEX "idx_cra_room_time" ON "class_room_assignments" ("kindergarten_id", "room_id", "start_at", "end_at");

CREATE INDEX "idx_cra_class_time" ON "class_room_assignments" ("kindergarten_id", "class_id", "start_at", "end_at");

CREATE UNIQUE INDEX "uq_camera_kg_cameraid" ON "cctv_cameras" ("kindergarten_id", "camera_id");

CREATE UNIQUE INDEX "uq_camera_kg_serialno" ON "cctv_cameras" ("kindergarten_id", "serial_no");

CREATE INDEX "idx_rca_camera_time" ON "room_camera_assignments" ("kindergarten_id", "camera_id", "start_at", "end_at");

CREATE INDEX "idx_rca_room_time" ON "room_camera_assignments" ("kindergarten_id", "room_id", "start_at", "end_at");

CREATE UNIQUE INDEX "uq_guardian_kg_guardianid" ON "guardians" ("kindergarten_id", "guardian_id");

CREATE UNIQUE INDEX "uq_guardian_user_id" ON "guardians" ("user_id");

CREATE INDEX "idx_cgr_child" ON "child_guardian_relationships" ("kindergarten_id", "child_id");

CREATE INDEX "idx_cgr_guardian" ON "child_guardian_relationships" ("kindergarten_id", "guardian_id");

CREATE INDEX "idx_cgr_child_primary" ON "child_guardian_relationships" ("kindergarten_id", "child_id", "is_primary");

CREATE UNIQUE INDEX "uq_ukm_kg_user" ON "user_kindergarten_memberships" ("kindergarten_id", "user_id");

CREATE UNIQUE INDEX "uq_ura_user_role_scope" ON "user_role_assignments" ("user_id", "role", "scope_type", "scope_id");

CREATE INDEX "idx_ura_scope_status" ON "user_role_assignments" ("scope_type", "scope_id", "status");

CREATE INDEX "idx_stream_camera" ON "camera_streams" ("kindergarten_id", "camera_id");

CREATE INDEX "idx_stream_camera_enabled" ON "camera_streams" ("kindergarten_id", "camera_id", "enabled");

CREATE INDEX "idx_stream_camera_primary" ON "camera_streams" ("kindergarten_id", "camera_id", "is_primary");

CREATE UNIQUE INDEX "uq_stream_kg_camera_streamid" ON "camera_streams" ("kindergarten_id", "camera_id", "stream_id");

CREATE UNIQUE INDEX "uq_session_kg_sessionid" ON "detection_sessions" ("kindergarten_id", "session_id");

CREATE INDEX "idx_session_camera_time" ON "detection_sessions" ("kindergarten_id", "camera_id", "started_at");

CREATE UNIQUE INDEX "uq_event_kg_eventid" ON "detection_events" ("kindergarten_id", "event_id");

CREATE INDEX "idx_event_room_time" ON "detection_events" ("kindergarten_id", "room_id", "detected_at");

CREATE INDEX "idx_event_camera_time" ON "detection_events" ("kindergarten_id", "camera_id", "detected_at");

CREATE INDEX "idx_event_status_time" ON "detection_events" ("kindergarten_id", "status", "detected_at");

CREATE INDEX "idx_review_event_time" ON "event_reviews" ("kindergarten_id", "event_id", "created_at");

CREATE INDEX "idx_evidence_event_time" ON "event_evidence_files" ("kindergarten_id", "event_id", "created_at");

CREATE UNIQUE INDEX "uq_device_tokens_platform_push_token" ON "device_tokens" ("platform", "push_token");

CREATE INDEX "idx_device_tokens_user_status" ON "device_tokens" ("user_id", "status");

CREATE INDEX "idx_rule_owner" ON "notification_rules" ("kindergarten_id", "user_id");

CREATE INDEX "idx_rule_enabled" ON "notification_rules" ("kindergarten_id", "enabled");

CREATE INDEX "idx_notif_recipient_time" ON "notifications" ("kindergarten_id", "recipient_user_id", "created_at");

CREATE INDEX "idx_notif_event" ON "notifications" ("kindergarten_id", "event_id");

CREATE INDEX "idx_notif_status_time" ON "notifications" ("kindergarten_id", "status", "created_at");

CREATE UNIQUE INDEX "uq_notifications_dedupe" ON "notifications" ("kindergarten_id", "dedupe_key");

COMMENT ON COLUMN "users"."user_id" IS '사용자 계정 ID';

COMMENT ON COLUMN "users"."login_id" IS '로그인 ID(사용자 식별자)';

COMMENT ON COLUMN "users"."email" IS '사용자 이메일';

COMMENT ON COLUMN "users"."phone" IS '사용자 휴대폰 번호';

COMMENT ON COLUMN "users"."password_hash" IS '비밀번호 해시';

COMMENT ON COLUMN "users"."status" IS '계정 상태';

COMMENT ON COLUMN "users"."last_login_at" IS '마지막 로그인 일시';

COMMENT ON COLUMN "users"."created_at" IS '생성 일시';

COMMENT ON COLUMN "users"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "kindergartens"."kindergarten_id" IS '유치원 ID';

COMMENT ON COLUMN "kindergartens"."name" IS '유치원명';

COMMENT ON COLUMN "kindergartens"."address" IS '주소';

COMMENT ON COLUMN "kindergartens"."region_code" IS '지역 코드(행정구역/내부 코드)';

COMMENT ON COLUMN "kindergartens"."code" IS '유치원 코드(내부/기관 식별용)';

COMMENT ON COLUMN "kindergartens"."business_registration_no" IS '사업자관리번호(유치원의 고유 사업자 등록 번호)';

COMMENT ON COLUMN "kindergartens"."contact_name" IS '담당자 이름';

COMMENT ON COLUMN "kindergartens"."contact_phone" IS '담당자 전화번호';

COMMENT ON COLUMN "kindergartens"."contact_email" IS '담당자 이메일';

COMMENT ON COLUMN "kindergartens"."status" IS '운영 상태';

COMMENT ON COLUMN "kindergartens"."created_at" IS '생성 일시';

COMMENT ON COLUMN "kindergartens"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "classes"."name" IS '반/학급 이름';

COMMENT ON COLUMN "classes"."grade" IS '학년/연령대(예: 만3/만4/만5)';

COMMENT ON COLUMN "classes"."academic_year" IS '학년도(예: 2026)';

COMMENT ON COLUMN "classes"."start_date" IS '운영 시작일';

COMMENT ON COLUMN "classes"."end_date" IS '운영 종료일';

COMMENT ON COLUMN "classes"."status" IS '운영 상태';

COMMENT ON COLUMN "classes"."created_at" IS '생성 일시';

COMMENT ON COLUMN "classes"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "children"."name" IS '원아 이름';

COMMENT ON COLUMN "children"."child_no" IS '원아 번호(원내 관리번호)';

COMMENT ON COLUMN "children"."rrn_encrypted" IS '주민등록번호 뒤자리 암호문(암호화 저장)';

COMMENT ON COLUMN "children"."rrn_first6" IS '주민등록번호 앞 6자리(생년월일, 검색/중복확인용)';

COMMENT ON COLUMN "children"."birth_date" IS '생년월일';

COMMENT ON COLUMN "children"."gender" IS '성별';

COMMENT ON COLUMN "children"."address" IS '주소';

COMMENT ON COLUMN "children"."enroll_date" IS '입원/등록일';

COMMENT ON COLUMN "children"."leave_date" IS '퇴원/전원/졸업일';

COMMENT ON COLUMN "children"."status" IS '재원 상태';

COMMENT ON COLUMN "children"."created_at" IS '생성 일시';

COMMENT ON COLUMN "children"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "child_class_assignments"."start_date" IS '배정 시작일';

COMMENT ON COLUMN "child_class_assignments"."end_date" IS '배정 종료일';

COMMENT ON COLUMN "child_class_assignments"."reason" IS '변경 사유(전반/이동/신설반 등)';

COMMENT ON COLUMN "child_class_assignments"."note" IS '비고/메모';

COMMENT ON COLUMN "child_class_assignments"."status" IS '배정 상태';

COMMENT ON COLUMN "child_class_assignments"."created_by_user_id" IS '생성자 사용자 ID';

COMMENT ON COLUMN "child_class_assignments"."created_at" IS '생성 일시';

COMMENT ON COLUMN "child_class_assignments"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "teachers"."staff_no" IS '직원 번호(원내 사번)';

COMMENT ON COLUMN "teachers"."name" IS '교사 이름';

COMMENT ON COLUMN "teachers"."gender" IS '성별';

COMMENT ON COLUMN "teachers"."emergency_contact_name" IS '비상 연락처 이름';

COMMENT ON COLUMN "teachers"."emergency_contact_phone" IS '비상 연락처 전화번호';

COMMENT ON COLUMN "teachers"."rrn_encrypted" IS '주민등록번호 암호문(암호화 저장)';

COMMENT ON COLUMN "teachers"."rrn_first6" IS '주민등록번호 앞 6자리(생년월일, 검색/중복확인용)';

COMMENT ON COLUMN "teachers"."level" IS '직급(예: 원장/부원장/일반교사 등)';

COMMENT ON COLUMN "teachers"."start_date" IS '근무 시작일';

COMMENT ON COLUMN "teachers"."end_date" IS '근무 종료일';

COMMENT ON COLUMN "teachers"."status" IS '재직 상태';

COMMENT ON COLUMN "teachers"."created_at" IS '생성 일시';

COMMENT ON COLUMN "teachers"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "superadmins"."superadmin_id" IS '슈퍼어드민 ID';

COMMENT ON COLUMN "superadmins"."user_id" IS '사용자 ID';

COMMENT ON COLUMN "superadmins"."name" IS '담당자 이름';

COMMENT ON COLUMN "superadmins"."department" IS '행정청+부서 이름 e.g.서울시청 아동담당관';

COMMENT ON COLUMN "superadmins"."created_at" IS '생성 일시';

COMMENT ON COLUMN "superadmins"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "class_teacher_assignments"."role" IS '반 내 역할(담임/부담임/보조 등)';

COMMENT ON COLUMN "class_teacher_assignments"."start_date" IS '배정 시작일';

COMMENT ON COLUMN "class_teacher_assignments"."end_date" IS '배정 종료일';

COMMENT ON COLUMN "class_teacher_assignments"."reason" IS '변경 사유';

COMMENT ON COLUMN "class_teacher_assignments"."note" IS '비고/메모';

COMMENT ON COLUMN "class_teacher_assignments"."status" IS '배정 상태';

COMMENT ON COLUMN "class_teacher_assignments"."created_by_user_id" IS '생성자 사용자 ID';

COMMENT ON COLUMN "class_teacher_assignments"."created_at" IS '생성 일시';

COMMENT ON COLUMN "class_teacher_assignments"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "rooms"."name" IS '공간/교실 이름';

COMMENT ON COLUMN "rooms"."room_code" IS '공간 코드(내부 식별용)';

COMMENT ON COLUMN "rooms"."location_note" IS '위치 설명(층/동/출입구 등)';

COMMENT ON COLUMN "rooms"."room_type" IS '공간 유형(교실/복도/현관/놀이터 등)';

COMMENT ON COLUMN "rooms"."status" IS '운영 상태';

COMMENT ON COLUMN "rooms"."created_at" IS '생성 일시';

COMMENT ON COLUMN "rooms"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "class_room_assignments"."assignment_id" IS '반-공간 배정 ID';

COMMENT ON COLUMN "class_room_assignments"."kindergarten_id" IS '유치원 ID(테넌트/필터링용)';

COMMENT ON COLUMN "class_room_assignments"."class_id" IS '반 ID';

COMMENT ON COLUMN "class_room_assignments"."room_id" IS '공간 ID';

COMMENT ON COLUMN "class_room_assignments"."start_at" IS '사용 시작 일시';

COMMENT ON COLUMN "class_room_assignments"."end_at" IS '사용 종료 일시, NULL=현재사용중';

COMMENT ON COLUMN "class_room_assignments"."purpose" IS '사용 목적(수업/체육/행사/기타)';

COMMENT ON COLUMN "class_room_assignments"."note" IS '비고/메모';

COMMENT ON COLUMN "class_room_assignments"."status" IS '배정 상태';

COMMENT ON COLUMN "class_room_assignments"."created_by_user_id" IS '생성자 사용자 ID';

COMMENT ON COLUMN "class_room_assignments"."created_at" IS '생성 일시';

COMMENT ON COLUMN "class_room_assignments"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "cctv_cameras"."camera_id" IS '카메라 ID';

COMMENT ON COLUMN "cctv_cameras"."kindergarten_id" IS '유치원 ID(KINDERGARTEN.kindergarten_id)';

COMMENT ON COLUMN "cctv_cameras"."serial_no" IS '카메라 시리얼 번호/제조사 식별자';

COMMENT ON COLUMN "cctv_cameras"."camera_name" IS '카메라 이름/별칭 또는 표시 이름';

COMMENT ON COLUMN "cctv_cameras"."model" IS '모델명';

COMMENT ON COLUMN "cctv_cameras"."created_by_user_id" IS '등록한 사용자 ID';

COMMENT ON COLUMN "cctv_cameras"."status" IS '운영 상태';

COMMENT ON COLUMN "cctv_cameras"."last_seen_at" IS '마지막 접속/하트비트 일시';

COMMENT ON COLUMN "cctv_cameras"."created_at" IS '생성 일시';

COMMENT ON COLUMN "cctv_cameras"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "room_camera_assignments"."start_at" IS '설치/배치 시작 일시';

COMMENT ON COLUMN "room_camera_assignments"."end_at" IS '설치/배치 종료 일시(철거/이동 시, NULL=현재 유효)';

COMMENT ON COLUMN "room_camera_assignments"."created_at" IS '생성 일시';

COMMENT ON COLUMN "room_camera_assignments"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "guardians"."name" IS '보호자 이름';

COMMENT ON COLUMN "guardians"."rrn_encrypted" IS '주민등록번호 암호문(암호화 저장)';

COMMENT ON COLUMN "guardians"."rrn_first6" IS '주민등록번호 앞 6자리(생년월일, 검색/중복확인용)';

COMMENT ON COLUMN "guardians"."gender" IS '성별';

COMMENT ON COLUMN "guardians"."address" IS '주소';

COMMENT ON COLUMN "guardians"."status" IS '보호자 상태';

COMMENT ON COLUMN "guardians"."created_at" IS '생성 일시';

COMMENT ON COLUMN "guardians"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "child_guardian_relationships"."relationship" IS '관계(부/모/조부모/후견인 등)';

COMMENT ON COLUMN "child_guardian_relationships"."is_primary" IS '주 보호자 여부';

COMMENT ON COLUMN "child_guardian_relationships"."priority" IS '우선순위(연락/권한 순서)';

COMMENT ON COLUMN "child_guardian_relationships"."start_date" IS '관계 시작일';

COMMENT ON COLUMN "child_guardian_relationships"."end_date" IS '관계 종료일';

COMMENT ON COLUMN "child_guardian_relationships"."created_at" IS '생성 일시';

COMMENT ON COLUMN "child_guardian_relationships"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "user_kindergarten_memberships"."membership_id" IS '멤버십 ID';

COMMENT ON COLUMN "user_kindergarten_memberships"."user_id" IS '사용자 ID(USER_ACCOUNT.user_id)';

COMMENT ON COLUMN "user_kindergarten_memberships"."kindergarten_id" IS '유치원 ID(KINDERGARTEN.kindergarten_id)';

COMMENT ON COLUMN "user_kindergarten_memberships"."status" IS '멤버십 상태';

COMMENT ON COLUMN "user_kindergarten_memberships"."joined_at" IS '가입/승인 일시';

COMMENT ON COLUMN "user_kindergarten_memberships"."left_at" IS '탈퇴/종료 일시';

COMMENT ON COLUMN "user_kindergarten_memberships"."created_at" IS '생성 일시';

COMMENT ON COLUMN "user_kindergarten_memberships"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "user_role_assignments"."role_assignment_id" IS '권한 할당 ID';

COMMENT ON COLUMN "user_role_assignments"."user_id" IS '대상 사용자 ID(USER_ACCOUNT.user_id)';

COMMENT ON COLUMN "user_role_assignments"."role" IS '역할(GUARDIAN/TEACHER/KINDERGARTEN_ADMIN/PLATFORM_IT_ADMIN/SUPERADMIN)';

COMMENT ON COLUMN "user_role_assignments"."scope_type" IS '권한 범위 유형(PLATFORM/KINDERGARTEN)';

COMMENT ON COLUMN "user_role_assignments"."scope_id" IS '권한 범위 ID(NULL=PLATFORM; KINDERGARTEN일 때 kindergarten_id)';

COMMENT ON COLUMN "user_role_assignments"."status" IS '권한 상태';

COMMENT ON COLUMN "user_role_assignments"."granted_at" IS '권한 부여 일시';

COMMENT ON COLUMN "user_role_assignments"."granted_by_user_id" IS '권한 부여자 사용자 ID(USER_ACCOUNT.user_id)';

COMMENT ON COLUMN "user_role_assignments"."revoked_at" IS '권한 회수 일시';

COMMENT ON COLUMN "camera_streams"."stream_id" IS '스트림 ID(다중 스트림 지원)';

COMMENT ON COLUMN "camera_streams"."kindergarten_id" IS '유치원 ID(KINDERGARTEN.kindergarten_id)';

COMMENT ON COLUMN "camera_streams"."camera_id" IS '카메라 ID(CCTV_CAMERA.camera_id)';

COMMENT ON COLUMN "camera_streams"."stream_type" IS '스트림 타입(메인/서브 등)';

COMMENT ON COLUMN "camera_streams"."stream_url" IS '스트림 URL(예: RTSP/HTTP 엔드포인트)';

COMMENT ON COLUMN "camera_streams"."stream_user" IS '스트림 인증 사용자명';

COMMENT ON COLUMN "camera_streams"."stream_password_encrypted" IS '스트림 인증 비밀번호(암호화 저장)';

COMMENT ON COLUMN "camera_streams"."protocol" IS '스트림 프로토콜(RTSP/HTTP)';

COMMENT ON COLUMN "camera_streams"."fps" IS '스트림 FPS(초당 프레임 수)';

COMMENT ON COLUMN "camera_streams"."resolution" IS '해상도(예: 1920x1080)';

COMMENT ON COLUMN "camera_streams"."is_primary" IS '대표 스트림 여부(카메라당 1개 권장)';

COMMENT ON COLUMN "camera_streams"."enabled" IS '스트림 사용 여부';

COMMENT ON COLUMN "camera_streams"."status" IS '스트림 상태(운영/비활성 등)';

COMMENT ON COLUMN "camera_streams"."created_at" IS '생성 일시';

COMMENT ON COLUMN "camera_streams"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "ai_models"."model_id" IS 'AI 모델 ID';

COMMENT ON COLUMN "ai_models"."name" IS '모델 이름';

COMMENT ON COLUMN "ai_models"."version" IS '모델 버전';

COMMENT ON COLUMN "ai_models"."status" IS '모델 상태';

COMMENT ON COLUMN "ai_models"."created_at" IS '생성 일시';

COMMENT ON COLUMN "ai_models"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "detection_sessions"."session_id" IS '탐지 세션 ID';

COMMENT ON COLUMN "detection_sessions"."kindergarten_id" IS '유치원 ID(KINDERGARTEN.kindergarten_id)';

COMMENT ON COLUMN "detection_sessions"."camera_id" IS '카메라 ID(CCTV_CAMERA.camera_id)';

COMMENT ON COLUMN "detection_sessions"."stream_id" IS '스트림 ID(CAMERA_STREAM.stream_id), 다중 스트림 중 선택';

COMMENT ON COLUMN "detection_sessions"."model_id" IS '모델 ID(AI_MODEL.model_id)';

COMMENT ON COLUMN "detection_sessions"."started_at" IS '세션 시작 일시';

COMMENT ON COLUMN "detection_sessions"."ended_at" IS '세션 종료 일시';

COMMENT ON COLUMN "detection_sessions"."status" IS '세션 상태';

COMMENT ON COLUMN "detection_sessions"."avg_latency_ms" IS '평균 지연 시간(ms)';

COMMENT ON COLUMN "detection_sessions"."inference_fps" IS '추론 처리 FPS';

COMMENT ON COLUMN "detection_events"."event_id" IS '탐지 이벤트 ID';

COMMENT ON COLUMN "detection_events"."kindergarten_id" IS '유치원 ID(KINDERGARTEN.kindergarten_id)';

COMMENT ON COLUMN "detection_events"."camera_id" IS '카메라 ID(CCTV_CAMERA.camera_id)';

COMMENT ON COLUMN "detection_events"."room_id" IS '룸/구역 ID(ROOM 테이블 FK 가정)';

COMMENT ON COLUMN "detection_events"."session_id" IS '탐지 세션 ID(DETECTION_SESSION.session_id)';

COMMENT ON COLUMN "detection_events"."event_type" IS '이벤트 유형(탐지 카테고리/코드)';

COMMENT ON COLUMN "detection_events"."severity" IS '심각도(정수 등급)';

COMMENT ON COLUMN "detection_events"."confidence" IS '신뢰도(0~1)';

COMMENT ON COLUMN "detection_events"."detected_at" IS '탐지 발생 일시';

COMMENT ON COLUMN "detection_events"."start_time" IS '이벤트 시작 시각';

COMMENT ON COLUMN "detection_events"."end_time" IS '이벤트 종료 시각';

COMMENT ON COLUMN "detection_events"."status" IS '이벤트 상태(세분화)';

COMMENT ON COLUMN "detection_events"."created_at" IS '생성 일시';

COMMENT ON COLUMN "detection_events"."updated_at" IS '수정 일시';

COMMENT ON COLUMN "event_reviews"."review_id" IS '이벤트 리뷰/처리 ID';

COMMENT ON COLUMN "event_reviews"."event_id" IS '이벤트 ID(DETECTION_EVENT.event_id)';

COMMENT ON COLUMN "event_reviews"."kindergarten_id" IS '유치원 ID(KINDERGARTEN.kindergarten_id)';

COMMENT ON COLUMN "event_reviews"."user_id" IS '처리 사용자 ID(USER_ACCOUNT.user_id)';

COMMENT ON COLUMN "event_reviews"."action" IS '처리 액션(ACK/RESOLVE/MARK_FALSE_POSITIVE/REOPEN)';

COMMENT ON COLUMN "event_reviews"."from_status" IS '처리 전 이벤트 상태';

COMMENT ON COLUMN "event_reviews"."result_status" IS '처리 결과 상태(액션 후 이벤트 상태 등)';

COMMENT ON COLUMN "event_reviews"."comment" IS '코멘트/메모';

COMMENT ON COLUMN "event_reviews"."created_at" IS '생성 일시';

COMMENT ON COLUMN "event_evidence_files"."evidence_id" IS '증거 자료 ID';

COMMENT ON COLUMN "event_evidence_files"."event_id" IS '이벤트 ID(DETECTION_EVENT.event_id)';

COMMENT ON COLUMN "event_evidence_files"."kindergarten_id" IS '유치원 ID(KINDERGARTEN.kindergarten_id)';

COMMENT ON COLUMN "event_evidence_files"."type" IS '증거 유형(IMAGE/VIDEO)';

COMMENT ON COLUMN "event_evidence_files"."storage_uri" IS '저장 위치 URI(internal MinIO/NAS 등)';

COMMENT ON COLUMN "event_evidence_files"."mime_type" IS 'MIME 타입(예: image/jpeg, video/mp4)';

COMMENT ON COLUMN "event_evidence_files"."created_at" IS '생성 일시';

COMMENT ON COLUMN "event_evidence_files"."retention_until" IS '보관 만료 예정 일시';

COMMENT ON COLUMN "event_evidence_files"."hold" IS '보관 홀드 여부(만료/삭제 방지 플래그)';

COMMENT ON COLUMN "event_evidence_files"."hash" IS '무결성 확인용 해시(파일 해시)';

COMMENT ON COLUMN "device_tokens"."device_id" IS '디바이스 토큰 ID';

COMMENT ON COLUMN "device_tokens"."user_id" IS '사용자 ID(USER_ACCOUNT.user_id)';

COMMENT ON COLUMN "device_tokens"."platform" IS '플랫폼(IOS/ANDROID)';

COMMENT ON COLUMN "device_tokens"."push_token" IS '푸시 토큰(APNs/FCM 등)';

COMMENT ON COLUMN "device_tokens"."status" IS '토큰 상태';

COMMENT ON COLUMN "device_tokens"."last_seen_at" IS '마지막 사용/갱신 일시';

COMMENT ON COLUMN "device_tokens"."created_at" IS '생성 일시';

COMMENT ON COLUMN "notification_rules"."rule_id" IS '알림 규칙 ID';

COMMENT ON COLUMN "notification_rules"."kindergarten_id" IS '유치원 ID(KINDERGARTEN.kindergarten_id)';

COMMENT ON COLUMN "notification_rules"."user_id" IS '규칙 소유/대상 사용자 ID(USER_ACCOUNT.user_id)';

COMMENT ON COLUMN "notification_rules"."target_type" IS '규칙 적용 범위(ROOM/CAMERA/KINDERGARTEN)';

COMMENT ON COLUMN "notification_rules"."target_id" IS '범위 ID(target_type에 따른 room_id/camera_id/kindergarten_id 등)';

COMMENT ON COLUMN "notification_rules"."event_type" IS '대상 이벤트 유형';

COMMENT ON COLUMN "notification_rules"."min_severity" IS '최소 심각도(이 값 이상만 알림)';

COMMENT ON COLUMN "notification_rules"."quiet_hours_json" IS '방해금지 시간 설정(JSON 문자열)';

COMMENT ON COLUMN "notification_rules"."enabled" IS '규칙 활성화 여부';

COMMENT ON COLUMN "notification_rules"."created_at" IS '생성 일시';

COMMENT ON COLUMN "notifications"."notification_id" IS '알림 ID';

COMMENT ON COLUMN "notifications"."kindergarten_id" IS '유치원 ID(KINDERGARTEN.kindergarten_id)';

COMMENT ON COLUMN "notifications"."event_id" IS '관련 이벤트 ID(DETECTION_EVENT.event_id)';

COMMENT ON COLUMN "notifications"."recipient_user_id" IS '수신자 사용자 ID(USER_ACCOUNT.user_id)';

COMMENT ON COLUMN "notifications"."channel" IS '전송 채널(PUSH/SMS/EMAIL)';

COMMENT ON COLUMN "notifications"."title" IS '알림 제목';

COMMENT ON COLUMN "notifications"."body" IS '알림 본문';

COMMENT ON COLUMN "notifications"."status" IS '전송 상태(세분화)';

COMMENT ON COLUMN "notifications"."dedupe_key" IS '중복 방지 키(멱등성 키, 애플리케이션에서 생성)';

COMMENT ON COLUMN "notifications"."sent_at" IS '전송 완료/시도 일시';

COMMENT ON COLUMN "notifications"."fail_reason" IS '실패 사유';

COMMENT ON COLUMN "notifications"."retry_count" IS '재시도 횟수';

COMMENT ON COLUMN "notifications"."created_at" IS '생성 일시';

COMMENT ON COLUMN "audit_logs"."audit_id" IS '감사/추적 로그 ID';

COMMENT ON COLUMN "audit_logs"."kindergarten_id" IS '유치원 ID(KINDERGARTEN.kindergarten_id)';

COMMENT ON COLUMN "audit_logs"."user_id" IS '행위 사용자 ID(USER_ACCOUNT.user_id)';

COMMENT ON COLUMN "audit_logs"."action" IS '행위(예: CREATE/UPDATE/DELETE/LOGIN 등)';

COMMENT ON COLUMN "audit_logs"."resource_type" IS '대상 리소스 유형(테이블/도메인명 등)';

COMMENT ON COLUMN "audit_logs"."resource_id" IS '대상 리소스 ID';

COMMENT ON COLUMN "audit_logs"."ip" IS '요청 IP';

COMMENT ON COLUMN "audit_logs"."user_agent" IS 'User-Agent';

COMMENT ON COLUMN "audit_logs"."created_at" IS '생성 일시';

ALTER TABLE "superadmins" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "classes" ADD FOREIGN KEY ("kindergarten_id") REFERENCES "kindergartens" ("kindergarten_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rooms" ADD FOREIGN KEY ("kindergarten_id") REFERENCES "kindergartens" ("kindergarten_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cctv_cameras" ADD FOREIGN KEY ("kindergarten_id") REFERENCES "kindergartens" ("kindergarten_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "teachers" ADD FOREIGN KEY ("kindergarten_id") REFERENCES "kindergartens" ("kindergarten_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "guardians" ADD FOREIGN KEY ("kindergarten_id") REFERENCES "kindergartens" ("kindergarten_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "children" ADD FOREIGN KEY ("kindergarten_id") REFERENCES "kindergartens" ("kindergarten_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "guardians" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "teachers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cctv_cameras" ADD FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "child_class_assignments" ADD FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "class_teacher_assignments" ADD FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "class_room_assignments" ADD FOREIGN KEY ("created_by_user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_role_assignments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_role_assignments" ADD FOREIGN KEY ("granted_by_user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_kindergarten_memberships" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_kindergarten_memberships" ADD FOREIGN KEY ("kindergarten_id") REFERENCES "kindergartens" ("kindergarten_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "camera_streams" ADD FOREIGN KEY ("kindergarten_id", "camera_id") REFERENCES "cctv_cameras" ("kindergarten_id", "camera_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "class_teacher_assignments" ADD FOREIGN KEY ("kindergarten_id", "class_id") REFERENCES "classes" ("kindergarten_id", "class_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "class_teacher_assignments" ADD FOREIGN KEY ("kindergarten_id", "teacher_id") REFERENCES "teachers" ("kindergarten_id", "teacher_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "child_guardian_relationships" ADD FOREIGN KEY ("kindergarten_id", "child_id") REFERENCES "children" ("kindergarten_id", "child_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "child_guardian_relationships" ADD FOREIGN KEY ("kindergarten_id", "guardian_id") REFERENCES "guardians" ("kindergarten_id", "guardian_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "class_room_assignments" ADD FOREIGN KEY ("kindergarten_id", "class_id") REFERENCES "classes" ("kindergarten_id", "class_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "class_room_assignments" ADD FOREIGN KEY ("kindergarten_id", "room_id") REFERENCES "rooms" ("kindergarten_id", "room_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "child_class_assignments" ADD FOREIGN KEY ("kindergarten_id", "child_id") REFERENCES "children" ("kindergarten_id", "child_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "child_class_assignments" ADD FOREIGN KEY ("kindergarten_id", "class_id") REFERENCES "classes" ("kindergarten_id", "class_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "room_camera_assignments" ADD FOREIGN KEY ("kindergarten_id", "room_id") REFERENCES "rooms" ("kindergarten_id", "room_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "room_camera_assignments" ADD FOREIGN KEY ("kindergarten_id", "camera_id") REFERENCES "cctv_cameras" ("kindergarten_id", "camera_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detection_sessions" ADD FOREIGN KEY ("kindergarten_id") REFERENCES "kindergartens" ("kindergarten_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detection_sessions" ADD FOREIGN KEY ("kindergarten_id", "camera_id") REFERENCES "cctv_cameras" ("kindergarten_id", "camera_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detection_sessions" ADD FOREIGN KEY ("kindergarten_id", "camera_id", "stream_id") REFERENCES "camera_streams" ("kindergarten_id", "camera_id", "stream_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detection_sessions" ADD FOREIGN KEY ("model_id") REFERENCES "ai_models" ("model_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detection_events" ADD FOREIGN KEY ("kindergarten_id", "session_id") REFERENCES "detection_sessions" ("kindergarten_id", "session_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detection_events" ADD FOREIGN KEY ("kindergarten_id", "camera_id") REFERENCES "cctv_cameras" ("kindergarten_id", "camera_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detection_events" ADD FOREIGN KEY ("kindergarten_id", "room_id") REFERENCES "rooms" ("kindergarten_id", "room_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "event_reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "event_reviews" ADD FOREIGN KEY ("kindergarten_id", "event_id") REFERENCES "detection_events" ("kindergarten_id", "event_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "event_evidence_files" ADD FOREIGN KEY ("kindergarten_id", "event_id") REFERENCES "detection_events" ("kindergarten_id", "event_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("kindergarten_id", "event_id") REFERENCES "detection_events" ("kindergarten_id", "event_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("recipient_user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notification_rules" ADD FOREIGN KEY ("kindergarten_id") REFERENCES "kindergartens" ("kindergarten_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notification_rules" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "device_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("kindergarten_id") REFERENCES "kindergartens" ("kindergarten_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") DEFERRABLE INITIALLY IMMEDIATE;
