

CREATE TABLE menu (
                      menu_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      parent_id BIGINT,
                      menu_name VARCHAR(100) NOT NULL,
                      menu_key VARCHAR(50) NOT NULL,
                      path VARCHAR(200),
                      component VARCHAR(200),
                      icon VARCHAR(50),
                      role_type VARCHAR(30) NOT NULL DEFAULT 'ALL',
                      sort_order INT NOT NULL DEFAULT 0,
                      is_active BOOLEAN NOT NULL DEFAULT TRUE,
                      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);




ALTER TABLE menu
ADD CONSTRAINT fk_menu_parent
FOREIGN KEY (parent_id)
REFERENCES menu(menu_id);



COMMENT ON TABLE menu IS '서비스 메뉴 및 권한 관리 테이블';
COMMENT ON COLUMN menu.menu_id IS '메뉴 고유 ID';
COMMENT ON COLUMN menu.parent_id IS '상위 메뉴 ID (자기참조)';
COMMENT ON COLUMN menu.menu_name IS '메뉴 표시 이름';
COMMENT ON COLUMN menu.menu_key IS '메뉴 고유 키 (개발용 식별자)';
COMMENT ON COLUMN menu.path IS '프론트 라우팅 경로';
COMMENT ON COLUMN menu.component IS '연결되는 프론트 컴포넌트';
COMMENT ON COLUMN menu.icon IS '메뉴 아이콘 키';
COMMENT ON COLUMN menu.role_type IS '접근 권한 구분';
COMMENT ON COLUMN menu.sort_order IS '메뉴 정렬 순서';
COMMENT ON COLUMN menu.is_active IS '메뉴 활성 여부';
COMMENT ON COLUMN menu.created_at IS '생성 일시';
COMMENT ON COLUMN menu.updated_at IS '수정 일시';


INSERT INTO menu
(menu_name, menu_key, path, component, icon, role_type, sort_order, created_at, updated_at)
VALUES
('대시보드', 'DASHBOARD', '/dashboard', 'DashboardPage', 'dashboard', 'ALL', 1, now(), now()),
('대시보드', 'DASHBOARD', '/dashboard', 'DashboardPage', 'dashboard', 'TEACHER', 1, now(), now()),

('회원관리', 'USER_MANAGE', '/users', 'UserManagePage', 'users', 'KINDERGARTEN_ADMIN', 2, now(), now()),
('회원관리', 'USER_MANAGE', '/users', 'UserManagePage', 'users', 'TEACHER', 2, now(), now()),

('아동관리', 'CHILD_MANAGE', '/children', 'ChildManagePage', 'child', 'KINDERGARTEN_ADMIN', 3, now(), now()),
('통계관리', 'STATISTICS', '/stats', 'StatisticsPage', 'chart', 'ADMIN', 4, now(), now()),

('설정', 'SETTING', '/setting', 'SettingPage', 'setting', 'ALL', 5, now(), now()),
('알림서비스', 'ALARM', '/alarm', 'AlarmPage', 'alarm', 'ALL', 6, now(), now()),
('감사편지', 'THANK_LETTER', '/letters', 'LetterPage', 'letterPage', 'ALL', 6, now(), now()),
('공지사항', 'ANNOUNCEMENTS', '/announcements', 'AnnouncementsPage', 'announcements', 'ALL', 7, now(), now());







