CREATE TABLE common_code (
code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
parent_code varchar(50),
code_group varchar(50) NOT NULL,
code varchar(50) NOT NULL,
code_name varchar(100) NOT NULL,
sort_order int NOT NULL DEFAULT 0,
is_active boolean NOT NULL DEFAULT true,
extra_json jsonb,
created_at timestamptz NOT NULL,
updated_at timestamptz NOT NULL
);

COMMENT ON COLUMN common_code.parent_code IS '상위 코드값 (예: MOTHER -> FEMALE 분류 등)';
COMMENT ON COLUMN common_code.code_group IS '코드 그룹 키 (예: GENDER, REGION, SCHOOL_STATUS)';
COMMENT ON COLUMN common_code.code IS '실제 코드값 (예: M, F / SEOUL / ELEMENTARY)';
COMMENT ON COLUMN common_code.code_name IS '화면 표시명 (예: 남, 여 / 서울 / 초등)';
COMMENT ON COLUMN common_code.sort_order IS '코드 정렬 순서';
COMMENT ON COLUMN common_code.is_active IS '코드 사용 여부';
COMMENT ON COLUMN common_code.extra_json IS '확장 정보(JSON 형태 메타데이터)';
COMMENT ON COLUMN common_code.created_at IS '생성 일시';
COMMENT ON COLUMN common_code.updated_at IS '수정 일시';

-- =========================================================
-- Signup common code seed data
-- =========================================================

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT NULL, 'GENDER', 'MALE', '남자', 1, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GENDER' AND code = 'MALE'
);

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT NULL, 'GENDER', 'FEMALE', '여자', 2, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GENDER' AND code = 'FEMALE'
);

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT 'FEMALE', 'GUARDIAN_RELATIONSHIP', 'MOTHER', '엄마', 1, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GUARDIAN_RELATIONSHIP' AND code = 'MOTHER'
);

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT 'MALE', 'GUARDIAN_RELATIONSHIP', 'FATHER', '아빠', 2, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GUARDIAN_RELATIONSHIP' AND code = 'FATHER'
);

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT 'FEMALE', 'GUARDIAN_RELATIONSHIP', 'MATERNAL_GRANDMOTHER', '외할머니', 3, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GUARDIAN_RELATIONSHIP' AND code = 'MATERNAL_GRANDMOTHER'
);

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT 'MALE', 'GUARDIAN_RELATIONSHIP', 'MATERNAL_GRANDFATHER', '외할아버지', 4, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GUARDIAN_RELATIONSHIP' AND code = 'MATERNAL_GRANDFATHER'
);

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT 'FEMALE', 'GUARDIAN_RELATIONSHIP', 'PATERNAL_GRANDMOTHER', '친할머니', 5, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GUARDIAN_RELATIONSHIP' AND code = 'PATERNAL_GRANDMOTHER'
);

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT 'MALE', 'GUARDIAN_RELATIONSHIP', 'PATERNAL_GRANDFATHER', '친할아버지', 6, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GUARDIAN_RELATIONSHIP' AND code = 'PATERNAL_GRANDFATHER'
);

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT NULL, 'GUARDIAN_RELATIONSHIP', 'OTHER', '기타', 99, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GUARDIAN_RELATIONSHIP' AND code = 'OTHER'
);
