CREATE TABLE common_code (
code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
parent_code varchar(50),
code_group varchar(50) NOT NULL,
code varchar(50) NOT NULL,
code_name varchar(100) NOT NULL,
sort_order int NOT NULL DEFAULT 0,
is_active boolean NOT NULL DEFAULT true,
extra_json jsonb,
created_at timestamptz NOT NULL,
updated_at timestamptz NOT NULL
);

COMMENT ON COLUMN common_code.parent_code IS '상위 코드값 (예: MOTHER -> FEMALE 분류 등)';
COMMENT ON COLUMN common_code.code_group IS '코드 그룹 키 (예: GENDER, REGION, SCHOOL_STATUS)';
COMMENT ON COLUMN common_code.code IS '실제 코드값 (예: M, F / SEOUL / ELEMENTARY)';
COMMENT ON COLUMN common_code.code_name IS '화면 표시명 (예: 남, 여 / 서울 / 초등)';
COMMENT ON COLUMN common_code.sort_order IS '코드 정렬 순서';
COMMENT ON COLUMN common_code.is_active IS '코드 사용 여부';
COMMENT ON COLUMN common_code.extra_json IS '확장 정보(JSON 형태 메타데이터)';
COMMENT ON COLUMN common_code.created_at IS '생성 일시';
COMMENT ON COLUMN common_code.updated_at IS '수정 일시';

-- =========================================================
-- Signup common code seed data
-- =========================================================

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT NULL, 'GENDER', 'MALE', '남자', 1, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GENDER' AND code = 'MALE'
);

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT NULL, 'GENDER', 'FEMALE', '여자', 2, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GENDER' AND code = 'FEMALE'
);

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT 'FEMALE', 'GUARDIAN_RELATIONSHIP', 'MOTHER', '엄마', 1, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GUARDIAN_RELATIONSHIP' AND code = 'MOTHER'
);

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT 'MALE', 'GUARDIAN_RELATIONSHIP', 'FATHER', '아빠', 2, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GUARDIAN_RELATIONSHIP' AND code = 'FATHER'
);

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT 'FEMALE', 'GUARDIAN_RELATIONSHIP', 'MATERNAL_GRANDMOTHER', '외할머니', 3, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GUARDIAN_RELATIONSHIP' AND code = 'MATERNAL_GRANDMOTHER'
);

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT 'MALE', 'GUARDIAN_RELATIONSHIP', 'MATERNAL_GRANDFATHER', '외할아버지', 4, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GUARDIAN_RELATIONSHIP' AND code = 'MATERNAL_GRANDFATHER'
);

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT 'FEMALE', 'GUARDIAN_RELATIONSHIP', 'PATERNAL_GRANDMOTHER', '친할머니', 5, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GUARDIAN_RELATIONSHIP' AND code = 'PATERNAL_GRANDMOTHER'
);

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT 'MALE', 'GUARDIAN_RELATIONSHIP', 'PATERNAL_GRANDFATHER', '친할아버지', 6, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GUARDIAN_RELATIONSHIP' AND code = 'PATERNAL_GRANDFATHER'
);

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT NULL, 'GUARDIAN_RELATIONSHIP', 'OTHER', '기타', 99, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_code WHERE code_group = 'GUARDIAN_RELATIONSHIP' AND code = 'OTHER'
);

-- =========================================================
-- Status code seed data by category
-- parent_code: status
-- =========================================================

INSERT INTO common_code (parent_code, code_group, code, code_name, sort_order, is_active, extra_json, created_at, updated_at)
SELECT 'status', v.code_group, v.code, v.code_name, v.sort_order, true, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM (
    VALUES
        ('user_account', 'ACTIVE', '활성', 1),
        ('user_account', 'PENDING', '대기', 2),
        ('user_account', 'DISABLED', '중지', 3),

        ('kindergarten', 'ACTIVE', '운영', 1),
        ('kindergarten', 'PENDING', '승인대기', 2),
        ('kindergarten', 'DISABLED', '폐업', 3),

        ('class_entity', 'ACTIVE', '운영', 1),
        ('class_entity', 'PENDING', '정지', 2),
        ('class_entity', 'DISABLED', '종료', 3),

        ('child', 'ACTIVE', '재원', 1),
        ('child', 'PENDING', '휴학', 2),
        ('child', 'DISABLED', '퇴원', 3),

        ('child_class_assignment', 'ACTIVE', '배정완료', 1),
        ('child_class_assignment', 'PENDING', '배정정지', 2),
        ('child_class_assignment', 'DISABLED', '배정해제', 3),

        ('teacher', 'ACTIVE', '재직', 1),
        ('teacher', 'PENDING', '휴직', 2),
        ('teacher', 'DISABLED', '퇴사', 3),

        ('class_teacher_assignment', 'ACTIVE', '배정완료', 1),
        ('class_teacher_assignment', 'PENDING', '배정정지', 2),
        ('class_teacher_assignment', 'DISABLED', '배정해제', 3),

        ('room', 'ACTIVE', '사용중', 1),
        ('room', 'PENDING', '정지', 2),
        ('room', 'DISABLED', '사용중지', 3),

        ('class_room_assignment', 'ACTIVE', '배정완료', 1),
        ('class_room_assignment', 'PENDING', '배정정지', 2),
        ('class_room_assignment', 'DISABLED', '배정해제', 3),

        ('cctv_camera', 'ACTIVE', '작동', 1),
        ('cctv_camera', 'PENDING', '정지', 2),
        ('cctv_camera', 'DISABLED', '중지', 3),

        ('guardian', 'ACTIVE', '활성', 1),
        ('guardian', 'PENDING', '대기', 2),
        ('guardian', 'DISABLED', '중지', 3),

        ('user_kindergarten_membership', 'ACTIVE', '활성', 1),
        ('user_kindergarten_membership', 'PENDING', '대기', 2),
        ('user_kindergarten_membership', 'DISABLED', '중지', 3),

        ('user_role_assignment', 'ACTIVE', '활성', 1),
        ('user_role_assignment', 'PENDING', '대기', 2),
        ('user_role_assignment', 'DISABLED', '중지', 3),

        ('ai_model', 'ACTIVE', '운영', 1),
        ('ai_model', 'PENDING', '대기', 2),
        ('ai_model', 'DISABLED', '비활성', 3),

        ('detection_session', 'ACTIVE', '진행중', 1),
        ('detection_session', 'PENDING', '대기', 2),
        ('detection_session', 'DISABLED', '종료', 3),

        ('detection_event', 'ACTIVE', '발생', 1),
        ('detection_event', 'PENDING', '대기', 2),
        ('detection_event', 'DISABLED', '종료', 3),

        ('event_review', 'ACTIVE', '검토중', 1),
        ('event_review', 'PENDING', '검토대기', 2),
        ('event_review', 'DISABLED', '검토종료', 3),

        ('device_token', 'ACTIVE', '활성', 1),
        ('device_token', 'PENDING', '대기', 2),
        ('device_token', 'DISABLED', '만료', 3),

        ('notification', 'ACTIVE', '발송', 1),
        ('notification', 'PENDING', '대기', 2),
        ('notification', 'DISABLED', '취소', 3)
) AS v(code_group, code, code_name, sort_order)
WHERE NOT EXISTS (
    SELECT 1
    FROM common_code c
    WHERE c.parent_code = 'status'
      AND c.code_group = v.code_group
      AND c.code = v.code
);
