

CREATE TABLE menu (
                      menu_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      parent_id BIGINT,
                      menu_name VARCHAR(100) NOT NULL,
                      menu_key VARCHAR(50) NOT NULL,
                      path VARCHAR(200),
                      component VARCHAR(200),
                      icon VARCHAR(50),
                      role_type VARCHAR(30) NOT NULL DEFAULT 'ALL',
                      sort_order INT NOT NULL DEFAULT 0,
                      is_active BOOLEAN NOT NULL DEFAULT TRUE,
                      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);




ALTER TABLE menu
ADD CONSTRAINT fk_menu_parent
FOREIGN KEY (parent_id)
REFERENCES menu(menu_id);



COMMENT ON TABLE menu IS '서비스 메뉴 및 권한 관리 테이블';
COMMENT ON COLUMN menu.menu_id IS '메뉴 고유 ID';
COMMENT ON COLUMN menu.parent_id IS '상위 메뉴 ID (자기참조)';
COMMENT ON COLUMN menu.menu_name IS '메뉴 표시 이름';
COMMENT ON COLUMN menu.menu_key IS '메뉴 고유 키 (개발용 식별자)';
COMMENT ON COLUMN menu.path IS '프론트 라우팅 경로';
COMMENT ON COLUMN menu.component IS '연결되는 프론트 컴포넌트';
COMMENT ON COLUMN menu.icon IS '메뉴 아이콘 키';
COMMENT ON COLUMN menu.role_type IS '접근 권한 구분';
COMMENT ON COLUMN menu.sort_order IS '메뉴 정렬 순서';
COMMENT ON COLUMN menu.is_active IS '메뉴 활성 여부';
COMMENT ON COLUMN menu.created_at IS '생성 일시';
COMMENT ON COLUMN menu.updated_at IS '수정 일시';

INSERT INTO public.menu (
    parent_id,
    menu_name,
    menu_key,
    path,
    component,
    icon,
    role_type,
    sort_order,
    is_active,
    created_at,
    updated_at
)
VALUES
    (NULL, '회원관리', 'USER_MANAGE', '/users', 'UserManagePage', 'users', 'KINDERGARTEN_ADMIN', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (NULL, '회원관리', 'USER_MANAGE', '/users', 'UserManagePage', 'users', 'TEACHER', 2, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (NULL, '아동관리', 'CHILD_MANAGE', '/children', 'ChildManagePage', 'child', 'KINDERGARTEN_ADMIN', 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (NULL, '통계관리', 'STATISTICS', '/stats', 'StatisticsPage', 'chart', 'KINDERGARTEN_ADMIN', 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (NULL, '설정', 'SETTING', '/setting', 'SettingPage', 'setting', 'ALL', 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (NULL, '공지사항', 'ANNOUNCEMENTS', '/announcements', 'AnnouncementsPage', 'announcements', 'ALL', 7, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (NULL, '알림서비스', 'DETECTION_EVENT', '/detectionEvent', 'DetectionEventPage', 'detectionEvent', 'SUPERADMIN', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (NULL, '알림서비스', 'DETECTION_EVENT', '/detectionEvent', 'DetectionEventPage', 'detectionEvent', 'KINDERGARTEN_ADMIN', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (NULL, '알림서비스', 'DETECTION_EVENT', '/detectionEvent', 'DetectionEventPage', 'detectionEvent', 'TEACHER', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (NULL, '알림서비스', 'DETECTION_EVENT', '/detectionEvent', 'DetectionEventPage', 'detectionEvent', 'GUARDIAN', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (NULL, '대시보드', 'CCTV_CAMERAS', '/cctvCameras', 'CctvCamerasPage', 'cctvCameras', 'KINDERGARTEN_ADMIN', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (NULL, '대시보드', 'CCTV_CAMERAS', '/cctvCameras', 'CctvCamerasPage', 'cctvCameras', 'TEACHER', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (NULL, '감사편지', 'APPRECIATION_LETTER', '/appreciationLetter', 'AppreciationLetterPage', 'appreciationLetter', 'ALL', 6, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);