CREATE TABLE common_codes (
code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
parent_code varchar(50),
code_group varchar(50) NOT NULL,
code varchar(50) NOT NULL,
code_name varchar(100) NOT NULL,
sort_order int NOT NULL DEFAULT 0,
is_active boolean NOT NULL DEFAULT true,
created_at timestamptz NOT NULL,
updated_at timestamptz NOT NULL
);

COMMENT ON COLUMN common_codes.parent_code IS '상위 코드값 (예: MOTHER -> FEMALE 분류 등)';
COMMENT ON COLUMN common_codes.code_group IS '코드 그룹 키 (예: GENDER, REGION, SCHOOL_STATUS)';
COMMENT ON COLUMN common_codes.code IS '실제 코드값 (예: M, F / SEOUL / ELEMENTARY)';
COMMENT ON COLUMN common_codes.code_name IS '화면 표시명 (예: 남, 여 / 서울 / 초등)';
COMMENT ON COLUMN common_codes.sort_order IS '코드 정렬 순서';
COMMENT ON COLUMN common_codes.is_active IS '코드 사용 여부';
COMMENT ON COLUMN common_codes.created_at IS '생성 일시';
COMMENT ON COLUMN common_codes.updated_at IS '수정 일시';

-- =========================================================
-- Signup common code seed data
-- =========================================================

INSERT INTO common_codes (parent_code, code_group, code, code_name, sort_order, is_active,  created_at, updated_at)
SELECT NULL, 'GENDER', 'MALE', '남자', 1, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_codes WHERE code_group = 'GENDER' AND code = 'MALE'
);

INSERT INTO common_codes (parent_code, code_group, code, code_name, sort_order, is_active,  created_at, updated_at)
SELECT NULL, 'GENDER', 'FEMALE', '여자', 2, true,  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_codes WHERE code_group = 'GENDER' AND code = 'FEMALE'
);

INSERT INTO common_codes (parent_code, code_group, code, code_name, sort_order, is_active,  created_at, updated_at)
SELECT 'FEMALE', 'GUARDIAN_RELATIONSHIP', 'MOTHER', '엄마', 1, true,  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_codes WHERE code_group = 'GUARDIAN_RELATIONSHIP' AND code = 'MOTHER'
);

INSERT INTO common_codes (parent_code, code_group, code, code_name, sort_order, is_active, created_at, updated_at)
SELECT 'MALE', 'GUARDIAN_RELATIONSHIP', 'FATHER', '아빠', 2, true,  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM common_codes WHERE code_group = 'GUARDIAN_RELATIONSHIP' AND code = 'FATHER'
);


-- =========================================================
-- Status code seed data by category
-- parent_code: status
-- =========================================================

INSERT INTO common_codes (parent_code, code_group, code, code_name, sort_order, is_active, created_at, updated_at)
SELECT 'status', v.code_group, v.code, v.code_name, v.sort_order, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM (
    VALUES
        ('user_account', 'ACTIVE', '활성', 1),
        ('user_account', 'PENDING', '대기', 2),
        ('user_account', 'DISABLED', '중지', 3),

        ('kindergartens', 'ACTIVE', '운영', 1),
        ('kindergartens', 'PENDING', '승인대기', 2),
        ('kindergartens', 'DISABLED', '폐업', 3),

        ('classes', 'ACTIVE', '운영', 1),
        ('classes', 'PENDING', '정지', 2),
        ('classes', 'DISABLED', '종료', 3),

        ('children', 'ACTIVE', '재원', 1),
        ('children', 'PENDING', '휴학', 2),
        ('children', 'DISABLED', '퇴원', 3),

        ('child_class_assignments', 'ACTIVE', '배정완료', 1),
        ('child_class_assignments', 'PENDING', '배정정지', 2),
        ('child_class_assignments', 'DISABLED', '배정해제', 3),

        ('teachers', 'ACTIVE', '재직', 1),
        ('teachers', 'PENDING', '휴직', 2),
        ('teachers', 'DISABLED', '퇴사', 3),

        ('class_teacher_assignments', 'ACTIVE', '배정완료', 1),
        ('class_teacher_assignments', 'PENDING', '배정정지', 2),
        ('class_teacher_assignments', 'DISABLED', '배정해제', 3),

        ('rooms', 'ACTIVE', '사용중', 1),
        ('rooms', 'PENDING', '정지', 2),
        ('rooms', 'DISABLED', '사용중지', 3),

        ('class_room_assignments', 'ACTIVE', '배정완료', 1),
        ('class_room_assignments', 'PENDING', '배정정지', 2),
        ('class_room_assignments', 'DISABLED', '배정해제', 3),

        ('cctv_cameras', 'ACTIVE', '작동', 1),
        ('cctv_cameras', 'PENDING', '정지', 2),
        ('cctv_cameras', 'DISABLED', '중지', 3),

        ('GUARDIAN', 'ACTIVE', '활성', 1),
        ('GUARDIAN', 'PENDING', '대기', 2),
        ('GUARDIAN', 'DISABLED', '중지', 3),

        ('user_kindergarten_memberships', 'ACTIVE', '활성', 1),
        ('user_kindergarten_memberships', 'PENDING', '대기', 2),
        ('user_kindergarten_memberships', 'DISABLED', '중지', 3),

        ('user_role_assignment', 'ACTIVE', '활성', 1),
        ('user_role_assignment', 'PENDING', '대기', 2),
        ('user_role_assignment', 'DISABLED', '중지', 3),

        ('ai_models', 'ACTIVE', '운영', 1),
        ('ai_models', 'PENDING', '대기', 2),
        ('ai_models', 'DISABLED', '비활성', 3),

        ('detection_sessions', 'ACTIVE', '진행중', 1),
        ('detection_sessions', 'PENDING', '대기', 2),
        ('detection_sessions', 'DISABLED', '종료', 3),

        ('detection_events', 'OPEN', '미확인', 10),
        ('detection_events', 'ACKNOWLEDGED', '확인됨', 20),
        ('detection_events', 'IN_REVIEW', '검토중', 30),
        ('detection_events', 'RESOLVED', '조치완료', 40),
        ('detection_events', 'DISMISSED', '오탐', 50),
        ('detection_events', 'ESCALATED', '상위보고', 60),

        ('event_reviews', 'ACTIVE', '검토중', 1),
        ('event_reviews', 'PENDING', '검토대기', 2),
        ('event_reviews', 'DISABLED', '검토종료', 3),

        ('device_tokens', 'ACTIVE', '활성', 1),
        ('device_tokens', 'PENDING', '대기', 2),
        ('device_tokens', 'DISABLED', '만료', 3),

        ('notifications', 'ACTIVE', '발송', 1),
        ('notifications', 'PENDING', '대기', 2),
        ('notifications', 'DISABLED', '취소', 3)
) AS v(code_group, code, code_name, sort_order)
WHERE NOT EXISTS (
    SELECT 1
    FROM common_codes c
    WHERE c.parent_code = 'status'
      AND c.code_group = v.code_group
      AND c.code = v.code
);



INSERT INTO common_codes
(
    parent_code,
    code_group,
    code,
    code_name,
    sort_order,
    is_active,
    created_at,
    updated_at
)
SELECT *
FROM (
    VALUES
    ('level', 'teachers', 'DIRECTOR', '원장', 1, true,  now(), now()),
    ('level', 'teachers', 'VICE_DIRECTOR', '부원장', 2, true,  now(), now()),
    ('level', 'teachers', 'TEACHER', '일반교사', 3, true,  now(), now())
) AS v(parent_code, code_group, code, code_name, sort_order, is_active,  created_at, updated_at)
WHERE NOT EXISTS (
    SELECT 1
    FROM common_codes c
    WHERE c.code_group = v.code_group
      AND c.code = v.code
);



INSERT INTO public.common_codes
(parent_code, code_group, code, code_name, sort_order, is_active, created_at, updated_at)
SELECT
    'status',
    'announcements',
    v.code,
    v.code_name,
    v.sort_order,
    true,
    now(),
    now()
FROM (
    VALUES
        ('ACTIVE', '게시 중', 1),
        ('PENDING', '게시 대기', 2),
        ('DISABLED', '게시 중지', 3)
) AS v(code, code_name, sort_order)
WHERE NOT EXISTS (
    SELECT 1
    FROM public.common_codes c
    WHERE c.parent_code = 'status'
      AND c.code_group = 'announcements'
      AND c.code = v.code
);


INSERT INTO public.common_codes
(parent_code, code_group, code, code_name, sort_order, is_active, created_at, updated_at)
SELECT
    'status',
    'user',
    v.code,
    v.code_name,
    v.sort_order,
    true,
    now(),
    now()
FROM (
    VALUES
        ('ACTIVE', '활성', 1),
        ('PENDING', '대기', 2),
        ('DISABLED', '종료', 3)
) AS v(code, code_name, sort_order)
WHERE NOT EXISTS (
    SELECT 1
    FROM public.common_codes c
    WHERE c.parent_code = 'status'
      AND c.code_group = 'user'
      AND c.code = v.code
);


--event_type 설정 (Assault,Fight,Burglary,Vandalism) 만 고려하기
INSERT INTO common_codes (
    parent_code,
    code_group,
    code,
    code_name,
    sort_order,
    is_active,
    created_at,
    updated_at
)
SELECT
    'event_type',
    v.code_group,
    v.code,
    v.code_name,
    v.sort_order,
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM (
         VALUES
             ('detection_events', 'ASSAULT', '폭행', 10),
             ('detection_events', 'FIGHT', '싸움', 20),
             ('detection_events', 'SWOON', '실신', 30),
             ('detection_events', 'KIDNAP', '납치', 40),

             ('detection_events', 'WANDER', '배회', 50),
             ('detection_events', 'TRESPASS', '침입', 60),
             ('detection_events', 'DATEFIGHT', '데이트폭력 및 추행', 70),
             ('detection_events', 'BURGLARY', '절도', 80),
             ('detection_events', 'VANDALISM', '기물파손', 90),
             ('detection_events', 'DUMP', '투기', 100),
             ('detection_events', 'ROBBERY', '강도', 110),
             ('detection_events', 'DRUNKEN', '주취행동', 120),
             ('detection_events', 'OTHER', '기타', 130)
     ) AS v(code_group, code, code_name, sort_order)
WHERE NOT EXISTS (
    SELECT 1
    FROM common_codes c
    WHERE c.parent_code = 'event_type'
      AND c.code_group = v.code_group
      AND c.code = v.code
);