#!/usr/bin/env bash
# Generate docs/engineering/schema-digest.md from the ACTUAL schema:
# initdb V1 baseline (+ seed) then Flyway delta migrations (V2+) applied via psql, then introspected.
# The migrations are the source of truth; regenerate this digest after any migration.
#
# Why: writing test fixtures / JPQL blind (grepping the DDL) caused real failures
# (UNIQUE(phone) collisions across the shared Testcontainer, the composite FK
# (kindergarten_id, event_id) -> detection_events, enum value casts). This digest
# surfaces those constraints in one place.
#
# Requires: Docker. Run via Git Bash from anywhere.
set -uo pipefail
# Stop Git Bash (MSYS) from rewriting container-side paths like /tmp and
# /docker-entrypoint-initdb.d into Windows paths in docker cp/exec/run args.
export MSYS_NO_PATHCONV=1

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && { pwd -W 2>/dev/null || pwd; })"
CID=kids-schema-digest-pg
OUT_REL="docs/engineering/schema-digest.md"
OUT="${REPO}/${OUT_REL}"

cleanup() { docker rm -f "$CID" >/dev/null 2>&1 || true; }
trap cleanup EXIT
cleanup

echo "Starting postgres with initdb (V1 baseline + seed)..."
MSYS_NO_PATHCONV=1 docker run -d --name "$CID" \
  -e POSTGRES_DB=kids_postgres_db -e POSTGRES_USER=kids_user -e POSTGRES_PASSWORD=kids_pass \
  -v "${REPO}/db/initdb:/docker-entrypoint-initdb.d:ro" \
  postgres:16-alpine >/dev/null

# The official postgres image runs a TEMPORARY server for initdb, then stops it and
# starts the real one. Wait for the init process to complete (past the temp server)...
echo "Waiting for initdb to complete..."
for i in $(seq 1 90); do
  docker logs "$CID" 2>&1 | grep -q "PostgreSQL init process complete" && break
  sleep 2
done
# ...then for the REAL server to accept a query (not just pg_isready on the temp server).
echo "Waiting for the real server..."
for i in $(seq 1 90); do
  docker exec "$CID" psql -U kids_user -d kids_postgres_db -c 'SELECT 1' >/dev/null 2>&1 && break
  sleep 2
done

echo "Applying Flyway delta migrations (all V*__*.sql except the V1 initdb baseline, in version order)..."
MIGDIR="${REPO}/backend/src/main/resources/db/migration"
while IFS= read -r f; do
  base="$(basename "$f")"
  case "$base" in V1__*) continue ;; esac   # V1 is the baseline, already applied via initdb
  echo "  applying ${base}"
  docker cp "$f" "${CID}:/tmp/${base}" >/dev/null
  docker exec "$CID" psql -v ON_ERROR_STOP=1 -U kids_user -d kids_postgres_db -f "/tmp/${base}" >/dev/null \
    || { echo "ERROR applying ${base}"; exit 1; }
done < <(ls -1 "${MIGDIR}"/V*__*.sql | sort -V)

echo "Introspecting schema -> ${OUT_REL}..."
docker exec -i "$CID" tee /tmp/introspect.sql >/dev/null <<'SQL'
\echo '# Schema digest (generated — do not edit by hand)'
\echo ''
\echo '> Generated by `scripts/schema-digest.sh` from the real schema (initdb V1 + Flyway V2/V3/V4).'
\echo '> The migrations are the source of truth; regenerate after any migration.'
\echo '> Use this when writing test fixtures / JPQL so you do not have to grep the DDL.'
\echo ''
\echo '## Enum types (use exact labels in `::enum` casts)'
\echo ''
SELECT format('- `%s`: %s', t.typname, string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder))
FROM pg_type t JOIN pg_enum e ON e.enumtypid = t.oid JOIN pg_namespace n ON n.oid = t.typnamespace
WHERE n.nspname = 'public' GROUP BY t.typname ORDER BY t.typname;
\echo ''
\echo '## Unique constraints / indexes (collision risk — fixtures must keep these distinct)'
\echo ''
\echo '| table | unique definition |'
\echo '| --- | --- |'
SELECT format('| %s | `%s` |', t.relname, regexp_replace(pg_get_indexdef(ix.indexrelid), '^.*USING [a-z]+ ', ''))
FROM pg_index ix JOIN pg_class i ON i.oid = ix.indexrelid JOIN pg_class t ON t.oid = ix.indrelid
JOIN pg_namespace n ON n.oid = t.relnamespace
WHERE ix.indisunique AND NOT ix.indisprimary AND n.nspname = 'public'
ORDER BY t.relname, i.relname;
\echo ''
\echo '## Foreign keys (composite FKs are a cross-tenant insert trap)'
\echo ''
\echo '| table | foreign key |'
\echo '| --- | --- |'
SELECT format('| %s | `%s` |', conrelid::regclass, pg_get_constraintdef(oid))
FROM pg_constraint WHERE contype = 'f' AND connamespace = 'public'::regnamespace
ORDER BY conrelid::regclass::text, conname;
\echo ''
\echo '## NOT NULL columns per table (required on INSERT)'
\echo ''
\echo '| table | NOT NULL columns |'
\echo '| --- | --- |'
SELECT format('| %s | %s |', table_name, string_agg(column_name, ', ' ORDER BY ordinal_position))
FROM information_schema.columns
WHERE table_schema = 'public' AND is_nullable = 'NO'
GROUP BY table_name ORDER BY table_name;
SQL

docker exec "$CID" psql -At -U kids_user -d kids_postgres_db -f /tmp/introspect.sql > "$OUT"
echo "Wrote ${OUT_REL} ($(wc -l < "$OUT") lines)"
