generatorName: spring
inputSpec: docs/OpenAPI/openapi.yaml
outputDir: generated/spring
templateDir: openapi-templates/spring

library: spring-boot

apiPackage: com.ai_kids_care.v1.api
modelPackage: com.ai_kids_care.v1.model
invokerPackage: com.ai_kids_care.v1.invoker

additionalProperties:
  hideGenerationTimestamp: true
  controllerPackage: com.ai_kids_care.v1.controller
  useSpringBoot3: true
  useTags: true
  delegatePattern: false
  useResponseEntity: false
  requestMappingMode: api_interface
  interfaceOnly: false
  skipDefaultInterface: true
  swagger2AnnotationLibrary: true

  lombok.RequiredArgsConstructor: true
  lombok.NoArgsConstructor: true
  lombok.ToString: true
  lombok.Data: true
  lombok.Builder: true
  useBeanValidation: false

  openApiNullable: false