/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.entity.AiModel;
import com.ai_kids_care.v1.dto.AiModelsCreateRequest;
import com.ai_kids_care.v1.dto.AiModelsUpdateRequest;
import com.ai_kids_care.v1.vo.ErrorResponse;
import com.ai_kids_care.v1.dto.PageOfAiModels;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "AiModels", description = "the AiModels API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface AiModelsApi {

    String PATH_CREATE_AI_MODELS = "/v1/ai_models";
    /**
     * POST /v1/ai_models : Create ai_models
     *
     * @param aiModelsCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createAiModels",
        summary = "Create ai_models",
        tags = { "AiModels" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AiModel.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AiModelsApi.PATH_CREATE_AI_MODELS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    AiModel createAiModels(
        @Parameter(name = "AiModelsCreateRequest", description = "", required = true) @RequestBody AiModelsCreateRequest aiModelsCreateRequest
    );


    String PATH_DELETE_AI_MODELS = "/v1/ai_models/{model_id}";
    /**
     * DELETE /v1/ai_models/{model_id} : Delete ai_models by model_id
     *
     * @param modelId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteAiModels",
        summary = "Delete ai_models by model_id",
        tags = { "AiModels" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = AiModelsApi.PATH_DELETE_AI_MODELS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteAiModels(
        @Parameter(name = "model_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("model_id") Long modelId
    );


    String PATH_GET_AI_MODELS = "/v1/ai_models/{model_id}";
    /**
     * GET /v1/ai_models/{model_id} : Get ai_models by model_id
     *
     * @param modelId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getAiModels",
        summary = "Get ai_models by model_id",
        tags = { "AiModels" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AiModel.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AiModelsApi.PATH_GET_AI_MODELS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    AiModel getAiModels(
        @Parameter(name = "model_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("model_id") Long modelId
    );


    String PATH_LIST_AI_MODELS = "/v1/ai_models";
    /**
     * GET /v1/ai_models : List ai_models
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listAiModels",
        summary = "List ai_models",
        tags = { "AiModels" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfAiModels.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AiModelsApi.PATH_LIST_AI_MODELS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfAiModels listAiModels(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_AI_MODELS = "/v1/ai_models/{model_id}";
    /**
     * PUT /v1/ai_models/{model_id} : Update ai_models by model_id
     *
     * @param modelId  (required)
     * @param aiModelsUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateAiModels",
        summary = "Update ai_models by model_id",
        tags = { "AiModels" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AiModel.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = AiModelsApi.PATH_UPDATE_AI_MODELS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    AiModel updateAiModels(
        @Parameter(name = "model_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("model_id") Long modelId,
        @Parameter(name = "AiModelsUpdateRequest", description = "", required = true) @RequestBody AiModelsUpdateRequest aiModelsUpdateRequest
    );

}
