/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.entity.AuditLogs;
import com.ai_kids_care.v1.dto.AuditLogsCreateRequest;
import com.ai_kids_care.v1.dto.AuditLogsUpdateRequest;
import com.ai_kids_care.v1.vo.ErrorResponse;
import com.ai_kids_care.v1.dto.PageOfAuditLogs;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "AuditLogs", description = "the AuditLogs API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface AuditLogsApi {

    String PATH_CREATE_AUDIT_LOGS = "/v1/audit_logs";
    /**
     * POST /v1/audit_logs : Create audit_logs
     *
     * @param auditLogsCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createAuditLogs",
        summary = "Create audit_logs",
        tags = { "AuditLogs" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuditLogs.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuditLogsApi.PATH_CREATE_AUDIT_LOGS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    AuditLogs createAuditLogs(
        @Parameter(name = "AuditLogsCreateRequest", description = "", required = true) @RequestBody AuditLogsCreateRequest auditLogsCreateRequest
    );


    String PATH_DELETE_AUDIT_LOGS = "/v1/audit_logs/{audit_id}";
    /**
     * DELETE /v1/audit_logs/{audit_id} : Delete audit_logs by audit_id
     *
     * @param auditId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteAuditLogs",
        summary = "Delete audit_logs by audit_id",
        tags = { "AuditLogs" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = AuditLogsApi.PATH_DELETE_AUDIT_LOGS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteAuditLogs(
        @Parameter(name = "audit_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("audit_id") Long auditId
    );


    String PATH_GET_AUDIT_LOGS = "/v1/audit_logs/{audit_id}";
    /**
     * GET /v1/audit_logs/{audit_id} : Get audit_logs by audit_id
     *
     * @param auditId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getAuditLogs",
        summary = "Get audit_logs by audit_id",
        tags = { "AuditLogs" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuditLogs.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AuditLogsApi.PATH_GET_AUDIT_LOGS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    AuditLogs getAuditLogs(
        @Parameter(name = "audit_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("audit_id") Long auditId
    );


    String PATH_LIST_AUDIT_LOGS = "/v1/audit_logs";
    /**
     * GET /v1/audit_logs : List audit_logs
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listAuditLogs",
        summary = "List audit_logs",
        tags = { "AuditLogs" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfAuditLogs.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AuditLogsApi.PATH_LIST_AUDIT_LOGS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfAuditLogs listAuditLogs(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_AUDIT_LOGS = "/v1/audit_logs/{audit_id}";
    /**
     * PUT /v1/audit_logs/{audit_id} : Update audit_logs by audit_id
     *
     * @param auditId  (required)
     * @param auditLogsUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateAuditLogs",
        summary = "Update audit_logs by audit_id",
        tags = { "AuditLogs" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuditLogs.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = AuditLogsApi.PATH_UPDATE_AUDIT_LOGS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    AuditLogs updateAuditLogs(
        @Parameter(name = "audit_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("audit_id") Long auditId,
        @Parameter(name = "AuditLogsUpdateRequest", description = "", required = true) @RequestBody AuditLogsUpdateRequest auditLogsUpdateRequest
    );

}
