/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.dto.*;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "Auth", description = "the Auth API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface AuthApi {

    String PATH_V1_AUTH_LOGIN_POST = "/v1/auth/login";

    /**
     * POST /v1/auth/login : Login
     *
     * @param authLoginRequest (required)
     * @return OK (status code 200)
     * or Invalid credentials or account not ACTIVE (status code 401)
     */
    @Operation(operationId = "AuthLogin", summary = "Login", tags = {"Auth"}, responses = {@ApiResponse(responseCode = "200", description = "OK", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = TokenResponse.class))}), @ApiResponse(responseCode = "401", description = "Invalid credentials or account not ACTIVE", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))})})
    @RequestMapping(method = RequestMethod.POST, value = AuthApi.PATH_V1_AUTH_LOGIN_POST, produces = {"application/json"}, consumes = {"application/json"})
    @ResponseStatus(HttpStatus.OK)
    ResponseEntity<TokenResponse> AuthLogin(@Parameter(name = "AuthLoginRequest", description = "", required = true) @RequestBody AuthLoginRequest authLoginRequest);


    String PATH_V1_AUTH_LOGOUT_POST = "/v1/auth/logout";

    /**
     * POST /v1/auth/logout : Logout (revoke refresh token)
     *
     * @param authLogoutRequest (required)
     * @return No Content (status code 204)
     */
    @Operation(operationId = "v1AuthLogoutPost", summary = "Logout (revoke refresh token)", tags = {"Auth"}, responses = {@ApiResponse(responseCode = "204", description = "No Content")})
    @RequestMapping(method = RequestMethod.POST, value = AuthApi.PATH_V1_AUTH_LOGOUT_POST, consumes = {"application/json"})
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void AuthLogoutPost(@Parameter(name = "AuthLogoutRequest", description = "", required = true) @RequestBody AuthLogoutRequest authLogoutRequest);


    String PATH_V1_AUTH_PASSWORD_PATCH = "/v1/auth/password";

    /**
     * PATCH /v1/auth/password : Change password (current password required)
     *
     * @param changePasswordRequest (required)
     * @return No Content (status code 204)
     * or Validation error (weak password, missing fields) (status code 400)
     * or Unauthorized (not logged in / invalid token) (status code 401)
     * or Current password mismatch (status code 403)
     */
    @Operation(operationId = "v1AuthPasswordPatch", summary = "Change password (current password required)", tags = {"Auth"}, responses = {@ApiResponse(responseCode = "204", description = "No Content"), @ApiResponse(responseCode = "400", description = "Validation error (weak password, missing fields)", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))}), @ApiResponse(responseCode = "401", description = "Unauthorized (not logged in / invalid token)"), @ApiResponse(responseCode = "403", description = "Current password mismatch", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))})})
    @RequestMapping(method = RequestMethod.PATCH, value = AuthApi.PATH_V1_AUTH_PASSWORD_PATCH, produces = {"application/json"}, consumes = {"application/json"})
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void AuthPasswordPatch(@Parameter(name = "ChangePasswordRequest", description = "", required = true) @RequestBody ChangePasswordRequest changePasswordRequest);


    String PATH_V1_AUTH_PASSWORD_RESETS_POST = "/v1/auth/password-resets";

    /**
     * POST /v1/auth/password-resets : Start forgot password flow
     * Always returns 200 to prevent account enumeration.
     *
     * @param authPasswordResetRequest (required)
     * @return OK (status code 200)
     */
    @Operation(operationId = "v1AuthPasswordResetsPost", summary = "Start forgot password flow", description = "Always returns 200 to prevent account enumeration.", tags = {"Auth"}, responses = {@ApiResponse(responseCode = "200", description = "OK", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = AuthPasswordResetsPost200Response.class))})})
    @RequestMapping(method = RequestMethod.POST, value = AuthApi.PATH_V1_AUTH_PASSWORD_RESETS_POST, produces = {"application/json"}, consumes = {"application/json"})
    @ResponseStatus(HttpStatus.OK)
    AuthPasswordResetsPost200Response v1AuthPasswordResetsPost(@Parameter(name = "AuthPasswordResetRequest", description = "", required = true) @RequestBody AuthPasswordResetRequest authPasswordResetRequest);


    String PATH_V1_AUTH_PASSWORD_RESETS_RESET_TOKEN_PATCH = "/v1/auth/password-resets/{resetToken}";

    /**
     * PATCH /v1/auth/password-resets/{resetToken} : Reset password with reset token
     *
     * @param resetToken           Password reset token from email/SMS link (required)
     * @param resetPasswordRequest (required)
     * @return No Content (status code 204)
     * or Invalid token / weak password (status code 400)
     */
    @Operation(operationId = "v1AuthPasswordResetsResetTokenPatch", summary = "Reset password with reset token", tags = {"Auth"}, responses = {@ApiResponse(responseCode = "204", description = "No Content"), @ApiResponse(responseCode = "400", description = "Invalid token / weak password", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))})})
    @RequestMapping(method = RequestMethod.PATCH, value = AuthApi.PATH_V1_AUTH_PASSWORD_RESETS_RESET_TOKEN_PATCH, produces = {"application/json"}, consumes = {"application/json"})
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void AuthPasswordResetsResetTokenPatch(@Parameter(name = "resetToken", description = "Password reset token from email/SMS link", required = true, in = ParameterIn.PATH) @PathVariable("resetToken") String resetToken, @Parameter(name = "ResetPasswordRequest", description = "", required = true) @RequestBody ResetPasswordRequest resetPasswordRequest);


    String PATH_V1_AUTH_REFRESH_POST = "/v1/auth/refresh";

    /**
     * POST /v1/auth/refresh : Refresh access token
     *
     * @param authRefreshRequest (required)
     * @return OK (status code 200)
     * or Invalid refresh token (status code 401)
     */
    @Operation(operationId = "v1AuthRefreshPost", summary = "Refresh access token", tags = {"Auth"}, responses = {@ApiResponse(responseCode = "200", description = "OK", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = TokenResponse.class))}), @ApiResponse(responseCode = "401", description = "Invalid refresh token", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))})})
    @RequestMapping(method = RequestMethod.POST, value = AuthApi.PATH_V1_AUTH_REFRESH_POST, produces = {"application/json"}, consumes = {"application/json"})
    @ResponseStatus(HttpStatus.OK)
    TokenResponse AuthRefreshPost(@Parameter(name = "AuthRefreshRequest", description = "", required = true) @RequestBody AuthRefreshRequest authRefreshRequest);


    String PATH_V1_AUTH_REGISTER_POST = "/v1/auth/register";

    /**
     * POST /v1/auth/register : Register user account
     *
     * @param authRegisterRequest (required)
     * @return Created (status code 201)
     * or Validation error (status code 400)
     * or Unique conflict (email/phone/loginId) (status code 409)
     */
    @Operation(operationId = "v1AuthRegisterPost", summary = "Register user account", tags = {"Auth"}, responses = {@ApiResponse(responseCode = "201", description = "Created", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = AuthRegisterResponse.class))}), @ApiResponse(responseCode = "400", description = "Validation error", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))}), @ApiResponse(responseCode = "409", description = "Unique conflict (email/phone/loginId)", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))})})
    @RequestMapping(method = RequestMethod.POST, value = AuthApi.PATH_V1_AUTH_REGISTER_POST, produces = {"application/json"}, consumes = {"application/json"})
    @ResponseStatus(HttpStatus.CREATED)
    AuthRegisterResponse AuthRegisterPost(@Parameter(name = "AuthRegisterRequest", description = "", required = true) @RequestBody AuthRegisterRequest authRegisterRequest);


    String PATH_V1_AUTH_VERIFICATION_CODES_CHALLENGE_ID_VERIFICATIONS_POST = "/v1/auth/verification-codes/{challengeId}/verifications";

    /**
     * POST /v1/auth/verification-codes/{challengeId}/verifications : Verify OTP code
     *
     * @param challengeId                   Verification challenge identifier returned by create endpoint (required)
     * @param verifyVerificationCodeRequest (required)
     * @return Verified. Returns a short-lived token for the next step. (status code 200)
     * or Invalid or expired code (or validation error) (status code 400)
     * or Too many attempts / rate limited (status code 429)
     */
    @Operation(operationId = "v1AuthVerificationCodesChallengeIdVerificationsPost", summary = "Verify OTP code", tags = {"Auth"}, responses = {@ApiResponse(responseCode = "200", description = "Verified. Returns a short-lived token for the next step.", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = VerifyVerificationCodeResponse.class))}), @ApiResponse(responseCode = "400", description = "Invalid or expired code (or validation error)", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))}), @ApiResponse(responseCode = "429", description = "Too many attempts / rate limited", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))})})
    @RequestMapping(method = RequestMethod.POST, value = AuthApi.PATH_V1_AUTH_VERIFICATION_CODES_CHALLENGE_ID_VERIFICATIONS_POST, produces = {"application/json"}, consumes = {"application/json"})
    @ResponseStatus(HttpStatus.OK)
    VerifyVerificationCodeResponse v1AuthVerificationCodesChallengeIdVerificationsPost(@Parameter(name = "challengeId", description = "Verification challenge identifier returned by create endpoint", required = true, in = ParameterIn.PATH) @PathVariable("challengeId") String challengeId, @Parameter(name = "VerifyVerificationCodeRequest", description = "", required = true) @RequestBody VerifyVerificationCodeRequest verifyVerificationCodeRequest);


    String PATH_V1_AUTH_VERIFICATION_CODES_POST = "/v1/auth/verification-codes";

    /**
     * POST /v1/auth/verification-codes : Send OTP verification code
     *
     * @param verificationCodeCreateRequest (required)
     * @return Created (status code 201)
     * or Rate limited (status code 429)
     */
    @Operation(operationId = "v1AuthVerificationCodesPost", summary = "Send OTP verification code", tags = {"Auth"}, responses = {@ApiResponse(responseCode = "201", description = "Created", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = VerificationCodeCreateResponse.class))}), @ApiResponse(responseCode = "429", description = "Rate limited", content = {@Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))})})
    @RequestMapping(method = RequestMethod.POST, value = AuthApi.PATH_V1_AUTH_VERIFICATION_CODES_POST, produces = {"application/json"}, consumes = {"application/json"})
    @ResponseStatus(HttpStatus.CREATED)
    VerificationCodeCreateResponse v1AuthVerificationCodesPost(@Parameter(name = "VerificationCodeCreateRequest", description = "", required = true) @RequestBody VerificationCodeCreateRequest verificationCodeCreateRequest);

}
