/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.entity.CameraStreams;
import com.ai_kids_care.v1.dto.CameraStreamsCreateRequest;
import com.ai_kids_care.v1.dto.CameraStreamsUpdateRequest;
import com.ai_kids_care.v1.vo.ErrorResponse;
import com.ai_kids_care.v1.entity.PageOfCameraStreams;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "CameraStreams", description = "the CameraStreams API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface CameraStreamsApi {

    String PATH_CREATE_CAMERA_STREAMS = "/v1/camera_streams";
    /**
     * POST /v1/camera_streams : Create camera_streams
     *
     * @param cameraStreamsCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createCameraStreams",
        summary = "Create camera_streams",
        tags = { "CameraStreams" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CameraStreams.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = CameraStreamsApi.PATH_CREATE_CAMERA_STREAMS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    CameraStreams createCameraStreams(
        @Parameter(name = "CameraStreamsCreateRequest", description = "", required = true) @RequestBody CameraStreamsCreateRequest cameraStreamsCreateRequest
    );


    String PATH_DELETE_CAMERA_STREAMS = "/v1/camera_streams/{stream_id}";
    /**
     * DELETE /v1/camera_streams/{stream_id} : Delete camera_streams by stream_id
     *
     * @param streamId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteCameraStreams",
        summary = "Delete camera_streams by stream_id",
        tags = { "CameraStreams" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = CameraStreamsApi.PATH_DELETE_CAMERA_STREAMS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteCameraStreams(
        @Parameter(name = "stream_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("stream_id") Long streamId
    );


    String PATH_GET_CAMERA_STREAMS = "/v1/camera_streams/{stream_id}";
    /**
     * GET /v1/camera_streams/{stream_id} : Get camera_streams by stream_id
     *
     * @param streamId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getCameraStreams",
        summary = "Get camera_streams by stream_id",
        tags = { "CameraStreams" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CameraStreams.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CameraStreamsApi.PATH_GET_CAMERA_STREAMS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    CameraStreams getCameraStreams(
        @Parameter(name = "stream_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("stream_id") Long streamId
    );


    String PATH_LIST_CAMERA_STREAMS = "/v1/camera_streams";
    /**
     * GET /v1/camera_streams : List camera_streams
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listCameraStreams",
        summary = "List camera_streams",
        tags = { "CameraStreams" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfCameraStreams.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CameraStreamsApi.PATH_LIST_CAMERA_STREAMS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfCameraStreams listCameraStreams(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_CAMERA_STREAMS = "/v1/camera_streams/{stream_id}";
    /**
     * PUT /v1/camera_streams/{stream_id} : Update camera_streams by stream_id
     *
     * @param streamId  (required)
     * @param cameraStreamsUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateCameraStreams",
        summary = "Update camera_streams by stream_id",
        tags = { "CameraStreams" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CameraStreams.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = CameraStreamsApi.PATH_UPDATE_CAMERA_STREAMS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    CameraStreams updateCameraStreams(
        @Parameter(name = "stream_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("stream_id") Long streamId,
        @Parameter(name = "CameraStreamsUpdateRequest", description = "", required = true) @RequestBody CameraStreamsUpdateRequest cameraStreamsUpdateRequest
    );

}
