/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.entity.CctvCameras;
import com.ai_kids_care.v1.dto.CctvCamerasCreateRequest;
import com.ai_kids_care.v1.dto.CctvCamerasUpdateRequest;
import com.ai_kids_care.v1.vo.ErrorResponse;
import com.ai_kids_care.v1.entity.PageOfCctvCameras;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "CctvCameras", description = "the CctvCameras API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface CctvCamerasApi {

    String PATH_CREATE_CCTV_CAMERAS = "/v1/cctv_cameras";
    /**
     * POST /v1/cctv_cameras : Create cctv_cameras
     *
     * @param cctvCamerasCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createCctvCameras",
        summary = "Create cctv_cameras",
        tags = { "CctvCameras" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CctvCameras.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = CctvCamerasApi.PATH_CREATE_CCTV_CAMERAS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    CctvCameras createCctvCameras(
        @Parameter(name = "CctvCamerasCreateRequest", description = "", required = true) @RequestBody CctvCamerasCreateRequest cctvCamerasCreateRequest
    );


    String PATH_DELETE_CCTV_CAMERAS = "/v1/cctv_cameras/{camera_id}";
    /**
     * DELETE /v1/cctv_cameras/{camera_id} : Delete cctv_cameras by camera_id
     *
     * @param cameraId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteCctvCameras",
        summary = "Delete cctv_cameras by camera_id",
        tags = { "CctvCameras" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = CctvCamerasApi.PATH_DELETE_CCTV_CAMERAS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteCctvCameras(
        @Parameter(name = "camera_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("camera_id") Long cameraId
    );


    String PATH_GET_CCTV_CAMERAS = "/v1/cctv_cameras/{camera_id}";
    /**
     * GET /v1/cctv_cameras/{camera_id} : Get cctv_cameras by camera_id
     *
     * @param cameraId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getCctvCameras",
        summary = "Get cctv_cameras by camera_id",
        tags = { "CctvCameras" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CctvCameras.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CctvCamerasApi.PATH_GET_CCTV_CAMERAS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    CctvCameras getCctvCameras(
        @Parameter(name = "camera_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("camera_id") Long cameraId
    );


    String PATH_LIST_CCTV_CAMERAS = "/v1/cctv_cameras";
    /**
     * GET /v1/cctv_cameras : List cctv_cameras
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listCctvCameras",
        summary = "List cctv_cameras",
        tags = { "CctvCameras" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfCctvCameras.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = CctvCamerasApi.PATH_LIST_CCTV_CAMERAS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfCctvCameras listCctvCameras(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_CCTV_CAMERAS = "/v1/cctv_cameras/{camera_id}";
    /**
     * PUT /v1/cctv_cameras/{camera_id} : Update cctv_cameras by camera_id
     *
     * @param cameraId  (required)
     * @param cctvCamerasUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateCctvCameras",
        summary = "Update cctv_cameras by camera_id",
        tags = { "CctvCameras" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CctvCameras.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = CctvCamerasApi.PATH_UPDATE_CCTV_CAMERAS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    CctvCameras updateCctvCameras(
        @Parameter(name = "camera_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("camera_id") Long cameraId,
        @Parameter(name = "CctvCamerasUpdateRequest", description = "", required = true) @RequestBody CctvCamerasUpdateRequest cctvCamerasUpdateRequest
    );

}
