/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.entity.ChildGuardianRelationships;
import com.ai_kids_care.v1.dto.ChildGuardianRelationshipsCreateRequest;
import com.ai_kids_care.v1.vo.ErrorResponse;
import com.ai_kids_care.v1.dto.PageOfChildGuardianRelationships;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "ChildGuardianRelationships", description = "the ChildGuardianRelationships API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface ChildGuardianRelationshipsApi {

    String PATH_CREATE_CHILD_GUARDIAN_RELATIONSHIPS = "/v1/child_guardian_relationships";
    /**
     * POST /v1/child_guardian_relationships : Create child_guardian_relationships
     *
     * @param childGuardianRelationshipsCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createChildGuardianRelationships",
        summary = "Create child_guardian_relationships",
        tags = { "ChildGuardianRelationships" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ChildGuardianRelationships.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ChildGuardianRelationshipsApi.PATH_CREATE_CHILD_GUARDIAN_RELATIONSHIPS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    ChildGuardianRelationships createChildGuardianRelationships(
        @Parameter(name = "ChildGuardianRelationshipsCreateRequest", description = "", required = true) @RequestBody ChildGuardianRelationshipsCreateRequest childGuardianRelationshipsCreateRequest
    );


    String PATH_DELETE_CHILD_GUARDIAN_RELATIONSHIPS_BY_KEY = "/v1/child_guardian_relationships/by-key";
    /**
     * DELETE /v1/child_guardian_relationships/by-key : Delete child_guardian_relationships by kindergarten_id,child_id,guardian_id
     *
     * @param kindergartenId  (required)
     * @param childId  (required)
     * @param guardianId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteChildGuardianRelationshipsByKey",
        summary = "Delete child_guardian_relationships by kindergarten_id,child_id,guardian_id",
        tags = { "ChildGuardianRelationships" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ChildGuardianRelationshipsApi.PATH_DELETE_CHILD_GUARDIAN_RELATIONSHIPS_BY_KEY,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteChildGuardianRelationshipsByKey(
        @Parameter(name = "kindergarten_id", description = "", required = true, in = ParameterIn.QUERY) @RequestParam(value = "kindergarten_id", required = true) Long kindergartenId,
        @Parameter(name = "child_id", description = "", required = true, in = ParameterIn.QUERY) @RequestParam(value = "child_id", required = true) Long childId,
        @Parameter(name = "guardian_id", description = "", required = true, in = ParameterIn.QUERY) @RequestParam(value = "guardian_id", required = true) Long guardianId
    );


    String PATH_GET_CHILD_GUARDIAN_RELATIONSHIPS_BY_KEY = "/v1/child_guardian_relationships/by-key";
    /**
     * GET /v1/child_guardian_relationships/by-key : Get child_guardian_relationships by kindergarten_id,child_id,guardian_id
     *
     * @param kindergartenId  (required)
     * @param childId  (required)
     * @param guardianId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getChildGuardianRelationshipsByKey",
        summary = "Get child_guardian_relationships by kindergarten_id,child_id,guardian_id",
        tags = { "ChildGuardianRelationships" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ChildGuardianRelationships.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ChildGuardianRelationshipsApi.PATH_GET_CHILD_GUARDIAN_RELATIONSHIPS_BY_KEY,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    ChildGuardianRelationships getChildGuardianRelationshipsByKey(
        @Parameter(name = "kindergarten_id", description = "", required = true, in = ParameterIn.QUERY) @RequestParam(value = "kindergarten_id", required = true) Long kindergartenId,
        @Parameter(name = "child_id", description = "", required = true, in = ParameterIn.QUERY) @RequestParam(value = "child_id", required = true) Long childId,
        @Parameter(name = "guardian_id", description = "", required = true, in = ParameterIn.QUERY) @RequestParam(value = "guardian_id", required = true) Long guardianId
    );


    String PATH_LIST_CHILD_GUARDIAN_RELATIONSHIPS = "/v1/child_guardian_relationships";
    /**
     * GET /v1/child_guardian_relationships : List child_guardian_relationships
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listChildGuardianRelationships",
        summary = "List child_guardian_relationships",
        tags = { "ChildGuardianRelationships" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfChildGuardianRelationships.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ChildGuardianRelationshipsApi.PATH_LIST_CHILD_GUARDIAN_RELATIONSHIPS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfChildGuardianRelationships listChildGuardianRelationships(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );

}
