/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.entity.ClassRoomAssignment;
import com.ai_kids_care.v1.dto.ClassRoomAssignmentsCreateRequest;
import com.ai_kids_care.v1.dto.ClassRoomAssignmentsUpdateRequest;
import com.ai_kids_care.v1.dto.ErrorResponse;
import com.ai_kids_care.v1.dto.PageOfClassRoomAssignments;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "ClassRoomAssignments", description = "the ClassRoomAssignments API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface ClassRoomAssignmentsApi {

    String PATH_CREATE_CLASS_ROOM_ASSIGNMENTS = "/v1/class_room_assignments";
    /**
     * POST /v1/class_room_assignments : Create class_room_assignments
     *
     * @param classRoomAssignmentsCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createClassRoomAssignments",
        summary = "Create class_room_assignments",
        tags = { "ClassRoomAssignments" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClassRoomAssignment.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ClassRoomAssignmentsApi.PATH_CREATE_CLASS_ROOM_ASSIGNMENTS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    ClassRoomAssignment createClassRoomAssignments(
        @Parameter(name = "ClassRoomAssignmentsCreateRequest", description = "", required = true) @RequestBody ClassRoomAssignmentsCreateRequest classRoomAssignmentsCreateRequest
    );


    String PATH_DELETE_CLASS_ROOM_ASSIGNMENTS = "/v1/class_room_assignments/{assignment_id}";
    /**
     * DELETE /v1/class_room_assignments/{assignment_id} : Delete class_room_assignments by assignment_id
     *
     * @param assignmentId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteClassRoomAssignments",
        summary = "Delete class_room_assignments by assignment_id",
        tags = { "ClassRoomAssignments" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ClassRoomAssignmentsApi.PATH_DELETE_CLASS_ROOM_ASSIGNMENTS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteClassRoomAssignments(
        @Parameter(name = "assignment_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("assignment_id") Long assignmentId
    );


    String PATH_GET_CLASS_ROOM_ASSIGNMENTS = "/v1/class_room_assignments/{assignment_id}";
    /**
     * GET /v1/class_room_assignments/{assignment_id} : Get class_room_assignments by assignment_id
     *
     * @param assignmentId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getClassRoomAssignments",
        summary = "Get class_room_assignments by assignment_id",
        tags = { "ClassRoomAssignments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClassRoomAssignment.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ClassRoomAssignmentsApi.PATH_GET_CLASS_ROOM_ASSIGNMENTS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    ClassRoomAssignment getClassRoomAssignments(
        @Parameter(name = "assignment_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("assignment_id") Long assignmentId
    );


    String PATH_LIST_CLASS_ROOM_ASSIGNMENTS = "/v1/class_room_assignments";
    /**
     * GET /v1/class_room_assignments : List class_room_assignments
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listClassRoomAssignments",
        summary = "List class_room_assignments",
        tags = { "ClassRoomAssignments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfClassRoomAssignments.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ClassRoomAssignmentsApi.PATH_LIST_CLASS_ROOM_ASSIGNMENTS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfClassRoomAssignments listClassRoomAssignments(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_CLASS_ROOM_ASSIGNMENTS = "/v1/class_room_assignments/{assignment_id}";
    /**
     * PUT /v1/class_room_assignments/{assignment_id} : Update class_room_assignments by assignment_id
     *
     * @param assignmentId  (required)
     * @param classRoomAssignmentsUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateClassRoomAssignments",
        summary = "Update class_room_assignments by assignment_id",
        tags = { "ClassRoomAssignments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClassRoomAssignment.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = ClassRoomAssignmentsApi.PATH_UPDATE_CLASS_ROOM_ASSIGNMENTS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    ClassRoomAssignment updateClassRoomAssignments(
        @Parameter(name = "assignment_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("assignment_id") Long assignmentId,
        @Parameter(name = "ClassRoomAssignmentsUpdateRequest", description = "", required = true) @RequestBody ClassRoomAssignmentsUpdateRequest classRoomAssignmentsUpdateRequest
    );

}
