/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.entity.DetectionSessions;
import com.ai_kids_care.v1.dto.DetectionSessionsCreateRequest;
import com.ai_kids_care.v1.dto.DetectionSessionsUpdateRequest;
import com.ai_kids_care.v1.vo.ErrorResponse;
import com.ai_kids_care.v1.dto.PageOfDetectionSessions;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "DetectionSessions", description = "the DetectionSessions API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface DetectionSessionsApi {

    String PATH_CREATE_DETECTION_SESSIONS = "/v1/detection_sessions";
    /**
     * POST /v1/detection_sessions : Create detection_sessions
     *
     * @param detectionSessionsCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createDetectionSessions",
        summary = "Create detection_sessions",
        tags = { "DetectionSessions" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DetectionSessions.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = DetectionSessionsApi.PATH_CREATE_DETECTION_SESSIONS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    DetectionSessions createDetectionSessions(
        @Parameter(name = "DetectionSessionsCreateRequest", description = "", required = true) @RequestBody DetectionSessionsCreateRequest detectionSessionsCreateRequest
    );


    String PATH_DELETE_DETECTION_SESSIONS = "/v1/detection_sessions/{session_id}";
    /**
     * DELETE /v1/detection_sessions/{session_id} : Delete detection_sessions by session_id
     *
     * @param sessionId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteDetectionSessions",
        summary = "Delete detection_sessions by session_id",
        tags = { "DetectionSessions" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = DetectionSessionsApi.PATH_DELETE_DETECTION_SESSIONS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteDetectionSessions(
        @Parameter(name = "session_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("session_id") Long sessionId
    );


    String PATH_GET_DETECTION_SESSIONS = "/v1/detection_sessions/{session_id}";
    /**
     * GET /v1/detection_sessions/{session_id} : Get detection_sessions by session_id
     *
     * @param sessionId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getDetectionSessions",
        summary = "Get detection_sessions by session_id",
        tags = { "DetectionSessions" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DetectionSessions.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = DetectionSessionsApi.PATH_GET_DETECTION_SESSIONS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    DetectionSessions getDetectionSessions(
        @Parameter(name = "session_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("session_id") Long sessionId
    );


    String PATH_LIST_DETECTION_SESSIONS = "/v1/detection_sessions";
    /**
     * GET /v1/detection_sessions : List detection_sessions
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listDetectionSessions",
        summary = "List detection_sessions",
        tags = { "DetectionSessions" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfDetectionSessions.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = DetectionSessionsApi.PATH_LIST_DETECTION_SESSIONS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfDetectionSessions listDetectionSessions(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_DETECTION_SESSIONS = "/v1/detection_sessions/{session_id}";
    /**
     * PUT /v1/detection_sessions/{session_id} : Update detection_sessions by session_id
     *
     * @param sessionId  (required)
     * @param detectionSessionsUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateDetectionSessions",
        summary = "Update detection_sessions by session_id",
        tags = { "DetectionSessions" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DetectionSessions.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = DetectionSessionsApi.PATH_UPDATE_DETECTION_SESSIONS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    DetectionSessions updateDetectionSessions(
        @Parameter(name = "session_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("session_id") Long sessionId,
        @Parameter(name = "DetectionSessionsUpdateRequest", description = "", required = true) @RequestBody DetectionSessionsUpdateRequest detectionSessionsUpdateRequest
    );

}
