/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.entity.DetectionEvent;
import com.ai_kids_care.v1.dto.DetectionEventsCreateRequest;
import com.ai_kids_care.v1.dto.DetectionEventsUpdateRequest;
import com.ai_kids_care.v1.dto.ErrorResponse;
import com.ai_kids_care.v1.dto.PageOfDetectionEvents;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "DetectionEvents", description = "the DetectionEvents API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface DetectionEventsApi {

    String PATH_CREATE_DETECTION_EVENTS = "/v1/detection_events";
    /**
     * POST /v1/detection_events : Create detection_events
     *
     * @param detectionEventsCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createDetectionEvents",
        summary = "Create detection_events",
        tags = { "DetectionEvents" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DetectionEvent.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = DetectionEventsApi.PATH_CREATE_DETECTION_EVENTS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    DetectionEvent createDetectionEvents(
        @Parameter(name = "DetectionEventsCreateRequest", description = "", required = true) @RequestBody DetectionEventsCreateRequest detectionEventsCreateRequest
    );


    String PATH_DELETE_DETECTION_EVENTS = "/v1/detection_events/{event_id}";
    /**
     * DELETE /v1/detection_events/{event_id} : Delete detection_events by event_id
     *
     * @param eventId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteDetectionEvents",
        summary = "Delete detection_events by event_id",
        tags = { "DetectionEvents" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = DetectionEventsApi.PATH_DELETE_DETECTION_EVENTS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteDetectionEvents(
        @Parameter(name = "event_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("event_id") Long eventId
    );


    String PATH_GET_DETECTION_EVENTS = "/v1/detection_events/{event_id}";
    /**
     * GET /v1/detection_events/{event_id} : Get detection_events by event_id
     *
     * @param eventId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getDetectionEvents",
        summary = "Get detection_events by event_id",
        tags = { "DetectionEvents" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DetectionEvent.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = DetectionEventsApi.PATH_GET_DETECTION_EVENTS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    DetectionEvent getDetectionEvents(
        @Parameter(name = "event_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("event_id") Long eventId
    );


    String PATH_LIST_DETECTION_EVENTS = "/v1/detection_events";
    /**
     * GET /v1/detection_events : List detection_events
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listDetectionEvents",
        summary = "List detection_events",
        tags = { "DetectionEvents" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfDetectionEvents.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = DetectionEventsApi.PATH_LIST_DETECTION_EVENTS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfDetectionEvents listDetectionEvents(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_DETECTION_EVENTS = "/v1/detection_events/{event_id}";
    /**
     * PUT /v1/detection_events/{event_id} : Update detection_events by event_id
     *
     * @param eventId  (required)
     * @param detectionEventsUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateDetectionEvents",
        summary = "Update detection_events by event_id",
        tags = { "DetectionEvents" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DetectionEvent.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = DetectionEventsApi.PATH_UPDATE_DETECTION_EVENTS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    DetectionEvent updateDetectionEvents(
        @Parameter(name = "event_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("event_id") Long eventId,
        @Parameter(name = "DetectionEventsUpdateRequest", description = "", required = true) @RequestBody DetectionEventsUpdateRequest detectionEventsUpdateRequest
    );

}
