/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.entity.DeviceToken;
import com.ai_kids_care.v1.dto.DeviceTokensCreateRequest;
import com.ai_kids_care.v1.dto.DeviceTokensUpdateRequest;
import com.ai_kids_care.v1.dto.ErrorResponse;
import com.ai_kids_care.v1.dto.PageOfDeviceTokens;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "DeviceTokens", description = "the DeviceTokens API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface DeviceTokensApi {

    String PATH_CREATE_DEVICE_TOKENS = "/v1/device_tokens";
    /**
     * POST /v1/device_tokens : Create device_tokens
     *
     * @param deviceTokensCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createDeviceTokens",
        summary = "Create device_tokens",
        tags = { "DeviceTokens" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DeviceToken.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = DeviceTokensApi.PATH_CREATE_DEVICE_TOKENS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    DeviceToken createDeviceTokens(
        @Parameter(name = "DeviceTokensCreateRequest", description = "", required = true) @RequestBody DeviceTokensCreateRequest deviceTokensCreateRequest
    );


    String PATH_DELETE_DEVICE_TOKENS = "/v1/device_tokens/{device_id}";
    /**
     * DELETE /v1/device_tokens/{device_id} : Delete device_tokens by device_id
     *
     * @param deviceId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteDeviceTokens",
        summary = "Delete device_tokens by device_id",
        tags = { "DeviceTokens" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = DeviceTokensApi.PATH_DELETE_DEVICE_TOKENS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteDeviceTokens(
        @Parameter(name = "device_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("device_id") Long deviceId
    );


    String PATH_GET_DEVICE_TOKENS = "/v1/device_tokens/{device_id}";
    /**
     * GET /v1/device_tokens/{device_id} : Get device_tokens by device_id
     *
     * @param deviceId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getDeviceTokens",
        summary = "Get device_tokens by device_id",
        tags = { "DeviceTokens" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DeviceToken.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = DeviceTokensApi.PATH_GET_DEVICE_TOKENS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    DeviceToken getDeviceTokens(
        @Parameter(name = "device_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("device_id") Long deviceId
    );


    String PATH_LIST_DEVICE_TOKENS = "/v1/device_tokens";
    /**
     * GET /v1/device_tokens : List device_tokens
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listDeviceTokens",
        summary = "List device_tokens",
        tags = { "DeviceTokens" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfDeviceTokens.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = DeviceTokensApi.PATH_LIST_DEVICE_TOKENS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfDeviceTokens listDeviceTokens(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_DEVICE_TOKENS = "/v1/device_tokens/{device_id}";
    /**
     * PUT /v1/device_tokens/{device_id} : Update device_tokens by device_id
     *
     * @param deviceId  (required)
     * @param deviceTokensUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateDeviceTokens",
        summary = "Update device_tokens by device_id",
        tags = { "DeviceTokens" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DeviceToken.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = DeviceTokensApi.PATH_UPDATE_DEVICE_TOKENS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    DeviceToken updateDeviceTokens(
        @Parameter(name = "device_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("device_id") Long deviceId,
        @Parameter(name = "DeviceTokensUpdateRequest", description = "", required = true) @RequestBody DeviceTokensUpdateRequest deviceTokensUpdateRequest
    );

}
