/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.vo.ErrorResponse;
import com.ai_kids_care.v1.entity.EventReviews;
import com.ai_kids_care.v1.dto.EventReviewsCreateRequest;
import com.ai_kids_care.v1.dto.EventReviewsUpdateRequest;
import com.ai_kids_care.v1.dto.PageOfEventReviews;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "EventReviews", description = "the EventReviews API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface EventReviewsApi {

    String PATH_CREATE_EVENT_REVIEWS = "/v1/event_reviews";
    /**
     * POST /v1/event_reviews : Create event_reviews
     *
     * @param eventReviewsCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createEventReviews",
        summary = "Create event_reviews",
        tags = { "EventReviews" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventReviews.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = EventReviewsApi.PATH_CREATE_EVENT_REVIEWS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    EventReviews createEventReviews(
        @Parameter(name = "EventReviewsCreateRequest", description = "", required = true) @RequestBody EventReviewsCreateRequest eventReviewsCreateRequest
    );


    String PATH_DELETE_EVENT_REVIEWS = "/v1/event_reviews/{review_id}";
    /**
     * DELETE /v1/event_reviews/{review_id} : Delete event_reviews by review_id
     *
     * @param reviewId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteEventReviews",
        summary = "Delete event_reviews by review_id",
        tags = { "EventReviews" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = EventReviewsApi.PATH_DELETE_EVENT_REVIEWS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteEventReviews(
        @Parameter(name = "review_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("review_id") Long reviewId
    );


    String PATH_GET_EVENT_REVIEWS = "/v1/event_reviews/{review_id}";
    /**
     * GET /v1/event_reviews/{review_id} : Get event_reviews by review_id
     *
     * @param reviewId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getEventReviews",
        summary = "Get event_reviews by review_id",
        tags = { "EventReviews" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventReviews.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = EventReviewsApi.PATH_GET_EVENT_REVIEWS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    EventReviews getEventReviews(
        @Parameter(name = "review_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("review_id") Long reviewId
    );


    String PATH_LIST_EVENT_REVIEWS = "/v1/event_reviews";
    /**
     * GET /v1/event_reviews : List event_reviews
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listEventReviews",
        summary = "List event_reviews",
        tags = { "EventReviews" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfEventReviews.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = EventReviewsApi.PATH_LIST_EVENT_REVIEWS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfEventReviews listEventReviews(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_EVENT_REVIEWS = "/v1/event_reviews/{review_id}";
    /**
     * PUT /v1/event_reviews/{review_id} : Update event_reviews by review_id
     *
     * @param reviewId  (required)
     * @param eventReviewsUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateEventReviews",
        summary = "Update event_reviews by review_id",
        tags = { "EventReviews" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = EventReviews.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = EventReviewsApi.PATH_UPDATE_EVENT_REVIEWS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    EventReviews updateEventReviews(
        @Parameter(name = "review_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("review_id") Long reviewId,
        @Parameter(name = "EventReviewsUpdateRequest", description = "", required = true) @RequestBody EventReviewsUpdateRequest eventReviewsUpdateRequest
    );

}
