/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.vo.ErrorResponse;
import com.ai_kids_care.v1.entity.Guardians;
import com.ai_kids_care.v1.dto.GuardiansCreateRequest;
import com.ai_kids_care.v1.dto.GuardiansUpdateRequest;
import com.ai_kids_care.v1.entity.PageOfGuardians;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "Guardians", description = "the Guardians API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface GuardiansApi {

    String PATH_CREATE_GUARDIANS = "/v1/guardians";
    /**
     * POST /v1/guardians : Create guardians
     *
     * @param guardiansCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createGuardians",
        summary = "Create guardians",
        tags = { "Guardians" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Guardians.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = GuardiansApi.PATH_CREATE_GUARDIANS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    Guardians createGuardians(
        @Parameter(name = "GuardiansCreateRequest", description = "", required = true) @RequestBody GuardiansCreateRequest guardiansCreateRequest
    );


    String PATH_DELETE_GUARDIANS = "/v1/guardians/{guardian_id}";
    /**
     * DELETE /v1/guardians/{guardian_id} : Delete guardians by guardian_id
     *
     * @param guardianId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteGuardians",
        summary = "Delete guardians by guardian_id",
        tags = { "Guardians" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = GuardiansApi.PATH_DELETE_GUARDIANS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteGuardians(
        @Parameter(name = "guardian_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("guardian_id") Long guardianId
    );


    String PATH_GET_GUARDIANS = "/v1/guardians/{guardian_id}";
    /**
     * GET /v1/guardians/{guardian_id} : Get guardians by guardian_id
     *
     * @param guardianId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getGuardians",
        summary = "Get guardians by guardian_id",
        tags = { "Guardians" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Guardians.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = GuardiansApi.PATH_GET_GUARDIANS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    Guardians getGuardians(
        @Parameter(name = "guardian_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("guardian_id") Long guardianId
    );


    String PATH_LIST_GUARDIANS = "/v1/guardians";
    /**
     * GET /v1/guardians : List guardians
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listGuardians",
        summary = "List guardians",
        tags = { "Guardians" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfGuardians.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = GuardiansApi.PATH_LIST_GUARDIANS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfGuardians listGuardians(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_GUARDIANS = "/v1/guardians/{guardian_id}";
    /**
     * PUT /v1/guardians/{guardian_id} : Update guardians by guardian_id
     *
     * @param guardianId  (required)
     * @param guardiansUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateGuardians",
        summary = "Update guardians by guardian_id",
        tags = { "Guardians" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Guardians.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = GuardiansApi.PATH_UPDATE_GUARDIANS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    Guardians updateGuardians(
        @Parameter(name = "guardian_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("guardian_id") Long guardianId,
        @Parameter(name = "GuardiansUpdateRequest", description = "", required = true) @RequestBody GuardiansUpdateRequest guardiansUpdateRequest
    );

}
