/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.vo.ErrorResponse;
import com.ai_kids_care.v1.entity.Kindergartens;
import com.ai_kids_care.v1.dto.KindergartensCreateRequest;
import com.ai_kids_care.v1.dto.KindergartensUpdateRequest;
import com.ai_kids_care.v1.entity.PageOfKindergartens;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "Kindergartens", description = "the Kindergartens API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface KindergartensApi {

    String PATH_CREATE_KINDERGARTENS = "/v1/kindergartens";
    /**
     * POST /v1/kindergartens : Create kindergartens
     *
     * @param kindergartensCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createKindergartens",
        summary = "Create kindergartens",
        tags = { "Kindergartens" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Kindergartens.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = KindergartensApi.PATH_CREATE_KINDERGARTENS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    Kindergartens createKindergartens(
        @Parameter(name = "KindergartensCreateRequest", description = "", required = true) @RequestBody KindergartensCreateRequest kindergartensCreateRequest
    );


    String PATH_DELETE_KINDERGARTENS = "/v1/kindergartens/{kindergarten_id}";
    /**
     * DELETE /v1/kindergartens/{kindergarten_id} : Delete kindergartens by kindergarten_id
     *
     * @param kindergartenId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteKindergartens",
        summary = "Delete kindergartens by kindergarten_id",
        tags = { "Kindergartens" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = KindergartensApi.PATH_DELETE_KINDERGARTENS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteKindergartens(
        @Parameter(name = "kindergarten_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("kindergarten_id") Long kindergartenId
    );


    String PATH_GET_KINDERGARTENS = "/v1/kindergartens/{kindergarten_id}";
    /**
     * GET /v1/kindergartens/{kindergarten_id} : Get kindergartens by kindergarten_id
     *
     * @param kindergartenId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getKindergartens",
        summary = "Get kindergartens by kindergarten_id",
        tags = { "Kindergartens" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Kindergartens.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = KindergartensApi.PATH_GET_KINDERGARTENS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    Kindergartens getKindergartens(
        @Parameter(name = "kindergarten_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("kindergarten_id") Long kindergartenId
    );


    String PATH_LIST_KINDERGARTENS = "/v1/kindergartens";
    /**
     * GET /v1/kindergartens : List kindergartens
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listKindergartens",
        summary = "List kindergartens",
        tags = { "Kindergartens" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfKindergartens.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = KindergartensApi.PATH_LIST_KINDERGARTENS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfKindergartens listKindergartens(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_KINDERGARTENS = "/v1/kindergartens/{kindergarten_id}";
    /**
     * PUT /v1/kindergartens/{kindergarten_id} : Update kindergartens by kindergarten_id
     *
     * @param kindergartenId  (required)
     * @param kindergartensUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateKindergartens",
        summary = "Update kindergartens by kindergarten_id",
        tags = { "Kindergartens" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Kindergartens.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = KindergartensApi.PATH_UPDATE_KINDERGARTENS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    Kindergartens updateKindergartens(
        @Parameter(name = "kindergarten_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("kindergarten_id") Long kindergartenId,
        @Parameter(name = "KindergartensUpdateRequest", description = "", required = true) @RequestBody KindergartensUpdateRequest kindergartensUpdateRequest
    );

}
