/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.vo.ErrorResponse;
import com.ai_kids_care.v1.entity.NotificationRules;
import com.ai_kids_care.v1.dto.NotificationRulesCreateRequest;
import com.ai_kids_care.v1.dto.NotificationRulesUpdateRequest;
import com.ai_kids_care.v1.dto.PageOfNotificationRules;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "NotificationRules", description = "the NotificationRules API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface NotificationRulesApi {

    String PATH_CREATE_NOTIFICATION_RULES = "/v1/notification_rules";
    /**
     * POST /v1/notification_rules : Create notification_rules
     *
     * @param notificationRulesCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createNotificationRules",
        summary = "Create notification_rules",
        tags = { "NotificationRules" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotificationRules.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = NotificationRulesApi.PATH_CREATE_NOTIFICATION_RULES,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    NotificationRules createNotificationRules(
        @Parameter(name = "NotificationRulesCreateRequest", description = "", required = true) @RequestBody NotificationRulesCreateRequest notificationRulesCreateRequest
    );


    String PATH_DELETE_NOTIFICATION_RULES = "/v1/notification_rules/{rule_id}";
    /**
     * DELETE /v1/notification_rules/{rule_id} : Delete notification_rules by rule_id
     *
     * @param ruleId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteNotificationRules",
        summary = "Delete notification_rules by rule_id",
        tags = { "NotificationRules" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = NotificationRulesApi.PATH_DELETE_NOTIFICATION_RULES,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteNotificationRules(
        @Parameter(name = "rule_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("rule_id") Long ruleId
    );


    String PATH_GET_NOTIFICATION_RULES = "/v1/notification_rules/{rule_id}";
    /**
     * GET /v1/notification_rules/{rule_id} : Get notification_rules by rule_id
     *
     * @param ruleId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getNotificationRules",
        summary = "Get notification_rules by rule_id",
        tags = { "NotificationRules" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotificationRules.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = NotificationRulesApi.PATH_GET_NOTIFICATION_RULES,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    NotificationRules getNotificationRules(
        @Parameter(name = "rule_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("rule_id") Long ruleId
    );


    String PATH_LIST_NOTIFICATION_RULES = "/v1/notification_rules";
    /**
     * GET /v1/notification_rules : List notification_rules
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listNotificationRules",
        summary = "List notification_rules",
        tags = { "NotificationRules" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfNotificationRules.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = NotificationRulesApi.PATH_LIST_NOTIFICATION_RULES,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfNotificationRules listNotificationRules(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_NOTIFICATION_RULES = "/v1/notification_rules/{rule_id}";
    /**
     * PUT /v1/notification_rules/{rule_id} : Update notification_rules by rule_id
     *
     * @param ruleId  (required)
     * @param notificationRulesUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateNotificationRules",
        summary = "Update notification_rules by rule_id",
        tags = { "NotificationRules" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = NotificationRules.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = NotificationRulesApi.PATH_UPDATE_NOTIFICATION_RULES,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    NotificationRules updateNotificationRules(
        @Parameter(name = "rule_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("rule_id") Long ruleId,
        @Parameter(name = "NotificationRulesUpdateRequest", description = "", required = true) @RequestBody NotificationRulesUpdateRequest notificationRulesUpdateRequest
    );

}
