/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.vo.ErrorResponse;
import com.ai_kids_care.v1.entity.Notifications;
import com.ai_kids_care.v1.dto.NotificationsCreateRequest;
import com.ai_kids_care.v1.dto.NotificationsUpdateRequest;
import com.ai_kids_care.v1.dto.PageOfNotifications;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "Notifications", description = "the Notifications API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface NotificationsApi {

    String PATH_CREATE_NOTIFICATIONS = "/v1/notifications";
    /**
     * POST /v1/notifications : Create notifications
     *
     * @param notificationsCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createNotifications",
        summary = "Create notifications",
        tags = { "Notifications" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Notifications.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = NotificationsApi.PATH_CREATE_NOTIFICATIONS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    Notifications createNotifications(
        @Parameter(name = "NotificationsCreateRequest", description = "", required = true) @RequestBody NotificationsCreateRequest notificationsCreateRequest
    );


    String PATH_DELETE_NOTIFICATIONS = "/v1/notifications/{notification_id}";
    /**
     * DELETE /v1/notifications/{notification_id} : Delete notifications by notification_id
     *
     * @param notificationId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteNotifications",
        summary = "Delete notifications by notification_id",
        tags = { "Notifications" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = NotificationsApi.PATH_DELETE_NOTIFICATIONS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteNotifications(
        @Parameter(name = "notification_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("notification_id") Long notificationId
    );


    String PATH_GET_NOTIFICATIONS = "/v1/notifications/{notification_id}";
    /**
     * GET /v1/notifications/{notification_id} : Get notifications by notification_id
     *
     * @param notificationId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getNotifications",
        summary = "Get notifications by notification_id",
        tags = { "Notifications" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Notifications.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = NotificationsApi.PATH_GET_NOTIFICATIONS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    Notifications getNotifications(
        @Parameter(name = "notification_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("notification_id") Long notificationId
    );


    String PATH_LIST_NOTIFICATIONS = "/v1/notifications";
    /**
     * GET /v1/notifications : List notifications
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listNotifications",
        summary = "List notifications",
        tags = { "Notifications" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfNotifications.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = NotificationsApi.PATH_LIST_NOTIFICATIONS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfNotifications listNotifications(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_NOTIFICATIONS = "/v1/notifications/{notification_id}";
    /**
     * PUT /v1/notifications/{notification_id} : Update notifications by notification_id
     *
     * @param notificationId  (required)
     * @param notificationsUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateNotifications",
        summary = "Update notifications by notification_id",
        tags = { "Notifications" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Notifications.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = NotificationsApi.PATH_UPDATE_NOTIFICATIONS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    Notifications updateNotifications(
        @Parameter(name = "notification_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("notification_id") Long notificationId,
        @Parameter(name = "NotificationsUpdateRequest", description = "", required = true) @RequestBody NotificationsUpdateRequest notificationsUpdateRequest
    );

}
