/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.dto.ErrorResponse;
import com.ai_kids_care.v1.dto.PageOfRooms;
import com.ai_kids_care.v1.entity.Room;
import com.ai_kids_care.v1.dto.RoomsCreateRequest;
import com.ai_kids_care.v1.dto.RoomsUpdateRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "Rooms", description = "the Rooms API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface RoomsApi {

    String PATH_CREATE_ROOMS = "/v1/rooms";
    /**
     * POST /v1/rooms : Create rooms
     *
     * @param roomsCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createRooms",
        summary = "Create rooms",
        tags = { "Rooms" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Room.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = RoomsApi.PATH_CREATE_ROOMS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    Room createRooms(
        @Parameter(name = "RoomsCreateRequest", description = "", required = true) @RequestBody RoomsCreateRequest roomsCreateRequest
    );


    String PATH_DELETE_ROOMS = "/v1/rooms/{room_id}";
    /**
     * DELETE /v1/rooms/{room_id} : Delete rooms by room_id
     *
     * @param roomId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteRooms",
        summary = "Delete rooms by room_id",
        tags = { "Rooms" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = RoomsApi.PATH_DELETE_ROOMS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteRooms(
        @Parameter(name = "room_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("room_id") Long roomId
    );


    String PATH_GET_ROOMS = "/v1/rooms/{room_id}";
    /**
     * GET /v1/rooms/{room_id} : Get rooms by room_id
     *
     * @param roomId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getRooms",
        summary = "Get rooms by room_id",
        tags = { "Rooms" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Room.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = RoomsApi.PATH_GET_ROOMS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    Room getRooms(
        @Parameter(name = "room_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("room_id") Long roomId
    );


    String PATH_LIST_ROOMS = "/v1/rooms";
    /**
     * GET /v1/rooms : List rooms
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listRooms",
        summary = "List rooms",
        tags = { "Rooms" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfRooms.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = RoomsApi.PATH_LIST_ROOMS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfRooms listRooms(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_ROOMS = "/v1/rooms/{room_id}";
    /**
     * PUT /v1/rooms/{room_id} : Update rooms by room_id
     *
     * @param roomId  (required)
     * @param roomsUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateRooms",
        summary = "Update rooms by room_id",
        tags = { "Rooms" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Room.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = RoomsApi.PATH_UPDATE_ROOMS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    Room updateRooms(
        @Parameter(name = "room_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("room_id") Long roomId,
        @Parameter(name = "RoomsUpdateRequest", description = "", required = true) @RequestBody RoomsUpdateRequest roomsUpdateRequest
    );

}
