/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.vo.ErrorResponse;
import com.ai_kids_care.v1.dto.PageOfSuperadmins;
import com.ai_kids_care.v1.entity.Superadmin;
import com.ai_kids_care.v1.dto.SuperadminsCreateRequest;
import com.ai_kids_care.v1.dto.SuperadminsUpdateRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "Superadmins", description = "the Superadmins API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface SuperadminsApi {

    String PATH_CREATE_SUPERADMINS = "/v1/superadmins";
    /**
     * POST /v1/superadmins : Create superadmins
     *
     * @param superadminsCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createSuperadmins",
        summary = "Create superadmins",
        tags = { "Superadmins" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Superadmin.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SuperadminsApi.PATH_CREATE_SUPERADMINS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    Superadmin createSuperadmins(
        @Parameter(name = "SuperadminsCreateRequest", description = "", required = true) @RequestBody SuperadminsCreateRequest superadminsCreateRequest
    );


    String PATH_DELETE_SUPERADMINS = "/v1/superadmins/{superadmin_id}";
    /**
     * DELETE /v1/superadmins/{superadmin_id} : Delete superadmins by superadmin_id
     *
     * @param superadminId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteSuperadmins",
        summary = "Delete superadmins by superadmin_id",
        tags = { "Superadmins" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = SuperadminsApi.PATH_DELETE_SUPERADMINS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteSuperadmins(
        @Parameter(name = "superadmin_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("superadmin_id") Long superadminId
    );


    String PATH_GET_SUPERADMINS = "/v1/superadmins/{superadmin_id}";
    /**
     * GET /v1/superadmins/{superadmin_id} : Get superadmins by superadmin_id
     *
     * @param superadminId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getSuperadmins",
        summary = "Get superadmins by superadmin_id",
        tags = { "Superadmins" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Superadmin.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SuperadminsApi.PATH_GET_SUPERADMINS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    Superadmin getSuperadmins(
        @Parameter(name = "superadmin_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("superadmin_id") Long superadminId
    );


    String PATH_LIST_SUPERADMINS = "/v1/superadmins";
    /**
     * GET /v1/superadmins : List superadmins
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listSuperadmins",
        summary = "List superadmins",
        tags = { "Superadmins" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfSuperadmins.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SuperadminsApi.PATH_LIST_SUPERADMINS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfSuperadmins listSuperadmins(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_SUPERADMINS = "/v1/superadmins/{superadmin_id}";
    /**
     * PUT /v1/superadmins/{superadmin_id} : Update superadmins by superadmin_id
     *
     * @param superadminId  (required)
     * @param superadminsUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateSuperadmins",
        summary = "Update superadmins by superadmin_id",
        tags = { "Superadmins" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Superadmin.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = SuperadminsApi.PATH_UPDATE_SUPERADMINS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    Superadmin updateSuperadmins(
        @Parameter(name = "superadmin_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("superadmin_id") Long superadminId,
        @Parameter(name = "SuperadminsUpdateRequest", description = "", required = true) @RequestBody SuperadminsUpdateRequest superadminsUpdateRequest
    );

}
