/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.vo.ErrorResponse;
import com.ai_kids_care.v1.dto.PageOfTeachers;
import com.ai_kids_care.v1.entity.Teachers;
import com.ai_kids_care.v1.dto.TeachersCreateRequest;
import com.ai_kids_care.v1.dto.TeachersUpdateRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "Teachers", description = "the Teachers API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface TeachersApi {

    String PATH_CREATE_TEACHERS = "/v1/teachers";
    /**
     * POST /v1/teachers : Create teachers
     *
     * @param teachersCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createTeachers",
        summary = "Create teachers",
        tags = { "Teachers" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Teachers.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = TeachersApi.PATH_CREATE_TEACHERS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    Teachers createTeachers(
        @Parameter(name = "TeachersCreateRequest", description = "", required = true) @RequestBody TeachersCreateRequest teachersCreateRequest
    );


    String PATH_DELETE_TEACHERS = "/v1/teachers/{teacher_id}";
    /**
     * DELETE /v1/teachers/{teacher_id} : Delete teachers by teacher_id
     *
     * @param teacherId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteTeachers",
        summary = "Delete teachers by teacher_id",
        tags = { "Teachers" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = TeachersApi.PATH_DELETE_TEACHERS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteTeachers(
        @Parameter(name = "teacher_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("teacher_id") Long teacherId
    );


    String PATH_GET_TEACHERS = "/v1/teachers/{teacher_id}";
    /**
     * GET /v1/teachers/{teacher_id} : Get teachers by teacher_id
     *
     * @param teacherId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getTeachers",
        summary = "Get teachers by teacher_id",
        tags = { "Teachers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Teachers.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = TeachersApi.PATH_GET_TEACHERS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    Teachers getTeachers(
        @Parameter(name = "teacher_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("teacher_id") Long teacherId
    );


    String PATH_LIST_TEACHERS = "/v1/teachers";
    /**
     * GET /v1/teachers : List teachers
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listTeachers",
        summary = "List teachers",
        tags = { "Teachers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfTeachers.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = TeachersApi.PATH_LIST_TEACHERS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfTeachers listTeachers(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_TEACHERS = "/v1/teachers/{teacher_id}";
    /**
     * PUT /v1/teachers/{teacher_id} : Update teachers by teacher_id
     *
     * @param teacherId  (required)
     * @param teachersUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateTeachers",
        summary = "Update teachers by teacher_id",
        tags = { "Teachers" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Teachers.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = TeachersApi.PATH_UPDATE_TEACHERS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    Teachers updateTeachers(
        @Parameter(name = "teacher_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("teacher_id") Long teacherId,
        @Parameter(name = "TeachersUpdateRequest", description = "", required = true) @RequestBody TeachersUpdateRequest teachersUpdateRequest
    );

}
