/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.vo.ErrorResponse;
import com.ai_kids_care.v1.dto.PageOfUserRoleAssignments;
import com.ai_kids_care.v1.entity.UserRoleAssignments;
import com.ai_kids_care.v1.dto.UserRoleAssignmentsCreateRequest;
import com.ai_kids_care.v1.dto.UserRoleAssignmentsUpdateRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "UserRoleAssignments", description = "the UserRoleAssignments API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface UserRoleAssignmentsApi {

    String PATH_CREATE_USER_ROLE_ASSIGNMENTS = "/v1/user_role_assignments";
    /**
     * POST /v1/user_role_assignments : Create user_role_assignments
     *
     * @param userRoleAssignmentsCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createUserRoleAssignments",
        summary = "Create user_role_assignments",
        tags = { "UserRoleAssignments" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserRoleAssignments.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = UserRoleAssignmentsApi.PATH_CREATE_USER_ROLE_ASSIGNMENTS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    UserRoleAssignments createUserRoleAssignments(
        @Parameter(name = "UserRoleAssignmentsCreateRequest", description = "", required = true) @RequestBody UserRoleAssignmentsCreateRequest userRoleAssignmentsCreateRequest
    );


    String PATH_DELETE_USER_ROLE_ASSIGNMENTS = "/v1/user_role_assignments/{role_assignment_id}";
    /**
     * DELETE /v1/user_role_assignments/{role_assignment_id} : Delete user_role_assignments by role_assignment_id
     *
     * @param roleAssignmentId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteUserRoleAssignments",
        summary = "Delete user_role_assignments by role_assignment_id",
        tags = { "UserRoleAssignments" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = UserRoleAssignmentsApi.PATH_DELETE_USER_ROLE_ASSIGNMENTS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteUserRoleAssignments(
        @Parameter(name = "role_assignment_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("role_assignment_id") Long roleAssignmentId
    );


    String PATH_GET_USER_ROLE_ASSIGNMENTS = "/v1/user_role_assignments/{role_assignment_id}";
    /**
     * GET /v1/user_role_assignments/{role_assignment_id} : Get user_role_assignments by role_assignment_id
     *
     * @param roleAssignmentId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getUserRoleAssignments",
        summary = "Get user_role_assignments by role_assignment_id",
        tags = { "UserRoleAssignments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserRoleAssignments.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = UserRoleAssignmentsApi.PATH_GET_USER_ROLE_ASSIGNMENTS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    UserRoleAssignments getUserRoleAssignments(
        @Parameter(name = "role_assignment_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("role_assignment_id") Long roleAssignmentId
    );


    String PATH_LIST_USER_ROLE_ASSIGNMENTS = "/v1/user_role_assignments";
    /**
     * GET /v1/user_role_assignments : List user_role_assignments
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listUserRoleAssignments",
        summary = "List user_role_assignments",
        tags = { "UserRoleAssignments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfUserRoleAssignments.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = UserRoleAssignmentsApi.PATH_LIST_USER_ROLE_ASSIGNMENTS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfUserRoleAssignments listUserRoleAssignments(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_USER_ROLE_ASSIGNMENTS = "/v1/user_role_assignments/{role_assignment_id}";
    /**
     * PUT /v1/user_role_assignments/{role_assignment_id} : Update user_role_assignments by role_assignment_id
     *
     * @param roleAssignmentId  (required)
     * @param userRoleAssignmentsUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateUserRoleAssignments",
        summary = "Update user_role_assignments by role_assignment_id",
        tags = { "UserRoleAssignments" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserRoleAssignments.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = UserRoleAssignmentsApi.PATH_UPDATE_USER_ROLE_ASSIGNMENTS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    UserRoleAssignments updateUserRoleAssignments(
        @Parameter(name = "role_assignment_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("role_assignment_id") Long roleAssignmentId,
        @Parameter(name = "UserRoleAssignmentsUpdateRequest", description = "", required = true) @RequestBody UserRoleAssignmentsUpdateRequest userRoleAssignmentsUpdateRequest
    );

}
