/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.20.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.ai_kids_care.v1.api;

import com.ai_kids_care.v1.vo.ErrorResponse;
import com.ai_kids_care.v1.dto.PageOfUserKindergartenMemberships;
import com.ai_kids_care.v1.entity.UserKindergartenMembership;
import com.ai_kids_care.v1.dto.UserKindergartenMembershipsCreateRequest;
import com.ai_kids_care.v1.dto.UserKindergartenMembershipsUpdateRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.*;

import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.20.0")

@Tag(name = "UserKindergartenMemberships", description = "the UserKindergartenMemberships API")
@RequestMapping("${openapi.aIKidsCare.base-path:/api}")
public interface UserKindergartenMembershipsApi {

    String PATH_CREATE_USER_KINDERGARTEN_MEMBERSHIPS = "/v1/user_kindergarten_memberships";
    /**
     * POST /v1/user_kindergarten_memberships : Create user_kindergarten_memberships
     *
     * @param userKindergartenMembershipsCreateRequest  (required)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "createUserKindergartenMemberships",
        summary = "Create user_kindergarten_memberships",
        tags = { "UserKindergartenMemberships" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserKindergartenMembership.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = UserKindergartenMembershipsApi.PATH_CREATE_USER_KINDERGARTEN_MEMBERSHIPS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    UserKindergartenMembership createUserKindergartenMemberships(
        @Parameter(name = "UserKindergartenMembershipsCreateRequest", description = "", required = true) @RequestBody UserKindergartenMembershipsCreateRequest userKindergartenMembershipsCreateRequest
    );


    String PATH_DELETE_USER_KINDERGARTEN_MEMBERSHIPS = "/v1/user_kindergarten_memberships/{membership_id}";
    /**
     * DELETE /v1/user_kindergarten_memberships/{membership_id} : Delete user_kindergarten_memberships by membership_id
     *
     * @param membershipId  (required)
     * @return No Content (status code 204)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteUserKindergartenMemberships",
        summary = "Delete user_kindergarten_memberships by membership_id",
        tags = { "UserKindergartenMemberships" },
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = UserKindergartenMembershipsApi.PATH_DELETE_USER_KINDERGARTEN_MEMBERSHIPS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteUserKindergartenMemberships(
        @Parameter(name = "membership_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("membership_id") Long membershipId
    );


    String PATH_GET_USER_KINDERGARTEN_MEMBERSHIPS = "/v1/user_kindergarten_memberships/{membership_id}";
    /**
     * GET /v1/user_kindergarten_memberships/{membership_id} : Get user_kindergarten_memberships by membership_id
     *
     * @param membershipId  (required)
     * @return OK (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getUserKindergartenMemberships",
        summary = "Get user_kindergarten_memberships by membership_id",
        tags = { "UserKindergartenMemberships" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserKindergartenMembership.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = UserKindergartenMembershipsApi.PATH_GET_USER_KINDERGARTEN_MEMBERSHIPS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    UserKindergartenMembership getUserKindergartenMemberships(
        @Parameter(name = "membership_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("membership_id") Long membershipId
    );


    String PATH_LIST_USER_KINDERGARTEN_MEMBERSHIPS = "/v1/user_kindergarten_memberships";
    /**
     * GET /v1/user_kindergarten_memberships : List user_kindergarten_memberships
     *
     * @param page  (optional)
     * @param size  (optional)
     * @param sort e.g. created_at,desc (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "listUserKindergartenMemberships",
        summary = "List user_kindergarten_memberships",
        tags = { "UserKindergartenMemberships" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PageOfUserKindergartenMemberships.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = UserKindergartenMembershipsApi.PATH_LIST_USER_KINDERGARTEN_MEMBERSHIPS,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    PageOfUserKindergartenMemberships listUserKindergartenMemberships(
        @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @RequestParam(value = "page", required = false) Integer page,
        @Parameter(name = "size", description = "", in = ParameterIn.QUERY) @RequestParam(value = "size", required = false) Integer size,
        @Parameter(name = "sort", description = "e.g. created_at,desc", in = ParameterIn.QUERY) @RequestParam(value = "sort", required = false) String sort
    );


    String PATH_UPDATE_USER_KINDERGARTEN_MEMBERSHIPS = "/v1/user_kindergarten_memberships/{membership_id}";
    /**
     * PUT /v1/user_kindergarten_memberships/{membership_id} : Update user_kindergarten_memberships by membership_id
     *
     * @param membershipId  (required)
     * @param userKindergartenMembershipsUpdateRequest  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Not Found (status code 404)
     *         or Conflict (status code 409)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "updateUserKindergartenMemberships",
        summary = "Update user_kindergarten_memberships by membership_id",
        tags = { "UserKindergartenMemberships" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserKindergartenMembership.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "409", description = "Conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = UserKindergartenMembershipsApi.PATH_UPDATE_USER_KINDERGARTEN_MEMBERSHIPS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    UserKindergartenMembership updateUserKindergartenMemberships(
        @Parameter(name = "membership_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("membership_id") Long membershipId,
        @Parameter(name = "UserKindergartenMembershipsUpdateRequest", description = "", required = true) @RequestBody UserKindergartenMembershipsUpdateRequest userKindergartenMembershipsUpdateRequest
    );

}
